apiVersion: gateway.api-platform.wso2.com/v1
kind: LlmProxy
metadata:
  name: support-proxy
spec:
  displayName: Support Proxy
  version: v1.0
  context: /support
  provider:
    id: mock-openai-provider
  policies:
    - name: api-key-auth
      version: v1
      paths:
        - path: /chat/completions
          methods: [POST]
          params:
            key: api_key
            in: header
    # Calculates the cost of each response.
    - name: llm-cost
      version: v1
      paths:
        - path: /chat/completions
          methods: [POST]
