{{- $ui := .Values -}}
{{- $tls := $ui.tls -}}
{{- if and $ui.deployment.enabled (eq $tls.certificateProvider "cert-manager") $tls.certManager.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "apip.developerPortal.fullname" . }}-tls
  labels:
    {{- include "apip.componentLabels" (list . "developer-portal" dict) | nindent 4 }}
  {{- with (include "apip.annotations" (list . dict)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "apip.developerPortal.fullname" . }}-tls
  commonName: {{ $tls.certManager.commonName }}
  dnsNames:
    {{- range $tls.certManager.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  duration: {{ $tls.certManager.duration | quote }}
  renewBefore: {{ $tls.certManager.renewBefore | quote }}
  issuerRef:
    {{- if $tls.certManager.createIssuer }}
    name: {{ include "apip.developerPortal.fullname" . }}-selfsigned-issuer
    {{- else }}
    name: {{ $tls.certManager.issuerRef.name }}
    {{- end }}
    kind: {{ $tls.certManager.issuerRef.kind }}
    {{- if $tls.certManager.issuerRef.group }}
    group: {{ $tls.certManager.issuerRef.group }}
    {{- end }}
  privateKey:
    algorithm: RSA
    size: 2048
{{- end }}

