/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package service

import (
	"fmt"
	"log/slog"
	"sort"
	"time"

	"github.com/wso2/api-platform/platform-api/config"
	"github.com/wso2/api-platform/platform-api/internal/apperror"
	"github.com/wso2/api-platform/platform-api/internal/constants"
	"github.com/wso2/api-platform/platform-api/internal/dto"
	"github.com/wso2/api-platform/platform-api/internal/model"
	"github.com/wso2/api-platform/platform-api/internal/repository"
	"github.com/wso2/api-platform/platform-api/internal/utils"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"
)

// ImportContext carries everything a per-kind importer needs to create or update
// an artifact pushed from a data-plane gateway.
type ImportContext struct {
	OrgID     string
	GatewayID string
	// MetadataMode is the last-in-wins decision for this push, computed by the
	// orchestrator for artifact-backed kinds from the existing working copy's
	// deployment time vs this push's DeployedAt. Org-level kinds not backed by the
	// artifacts table (LLM Provider Templates) compute their own decision in the
	// importer using DeployedAt.
	MetadataMode utils.MetadataWriteMode

	// ID is the control-plane artifact UUID: reused when the artifact already exists
	// (matched by handle), otherwise freshly generated by the orchestrator. It is NOT
	// the data-plane UUID — the CP owns its own identifier.
	ID string
	// DPID is the data-plane (gateway) artifact UUID as pushed. It is informational
	// (logging/traceability) and is never used as the CP artifact UUID.
	DPID          string
	Configuration dto.ArtifactImportConfig
	Status        string // deployed|pending|failed|undeployed (as pushed)
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeployedAt    *time.Time
	Properties    map[string]interface{}

	ProjectName string // metadata.project (may be empty)
	ProjectID   string // resolved project UUID (empty for org-level kinds)

	// Existing is the already-stored artifacts-table row keyed by ID, or nil if new.
	// It is nil for organization-level kinds that are not backed by the artifacts
	// table (e.g. LLM Provider Templates); those importers resolve existence themselves.
	Existing *model.Artifact
}

// ImportResult is returned by an importer describing the persisted artifact.
type ImportResult struct {
	ID              string
	DeployedVersion string
	// Deployable indicates the artifact has a per-gateway deployment lifecycle and
	// therefore a deployment record + status row should be written by the orchestrator.
	Deployable bool
}

// GatewayArtifactImporter is the contract every artifact kind implements so the
// DP->CP import flow stays generic and open to new kinds.
type GatewayArtifactImporter interface {
	// Kind returns the artifact kind string this importer handles (see constants).
	Kind() string
	// RequiresProject reports whether metadata.project must be present and resolvable.
	RequiresProject() bool
	// Import creates or updates the artifact and returns the persisted result.
	Import(ctx *ImportContext) (*ImportResult, error)
}

// ArtifactImportService resolves the correct importer for a pushed artifact and
// runs the shared pre/post processing (gateway auth, project resolution,
// deployment/status persistence).
type ArtifactImportService struct {
	importers      map[string]GatewayArtifactImporter
	gatewayRepo    repository.GatewayRepository
	projectRepo    repository.ProjectRepository
	artifactRepo   repository.ArtifactRepository
	deploymentRepo repository.DeploymentRepository
	apiRepo        repository.APIRepository
	cfg            *config.Server
	slogger        *slog.Logger
}

// NewArtifactImportService builds the import service and registers an importer for
// every supported artifact kind. Adding a new kind is a matter of registering a
// new importer here — no changes to the endpoint or orchestrator are required.
func NewArtifactImportService(
	apiRepo repository.APIRepository,
	providerRepo repository.LLMProviderRepository,
	templateRepo repository.LLMProviderTemplateRepository,
	proxyRepo repository.LLMProxyRepository,
	mcpProxyRepo repository.MCPProxyRepository,
	artifactRepo repository.ArtifactRepository,
	deploymentRepo repository.DeploymentRepository,
	gatewayRepo repository.GatewayRepository,
	projectRepo repository.ProjectRepository,
	cfg *config.Server,
	slogger *slog.Logger,
	mcpServerInfo MCPServerInfoFetcher,
) *ArtifactImportService {
	s := &ArtifactImportService{
		gatewayRepo:    gatewayRepo,
		projectRepo:    projectRepo,
		artifactRepo:   artifactRepo,
		deploymentRepo: deploymentRepo,
		apiRepo:        apiRepo,
		cfg:            cfg,
		slogger:        slogger,
	}
	s.importers = map[string]GatewayArtifactImporter{
		constants.RestApi:             newRestAPIImporter(apiRepo, artifactRepo),
		constants.LLMProvider:         newLLMProviderImporter(providerRepo, templateRepo, artifactRepo, cfg, slogger),
		constants.LLMProviderTemplate: newLLMProviderTemplateImporter(templateRepo),
		constants.LLMProxy:            newLLMProxyImporter(proxyRepo, providerRepo, artifactRepo),
		constants.MCPProxy:            newMCPProxyImporter(mcpProxyRepo, artifactRepo, mcpServerInfo),
	}
	return s
}

// ImportArtifacts imports a batch of gateway-pushed artifacts. It creates them in dependency
// order (see artifactImportOrder) and is continue-on-error: a failure to import one artifact
// is recorded against that artifact's dpid and does not abort the rest. The returned response
// maps each artifact's dpid to its per-artifact result (a non-empty Error marks a failure)
// alongside total/success/failed counts.
func (s *ArtifactImportService) ImportArtifacts(orgID, gatewayID string, reqs []dto.ImportGatewayArtifactRequest) *dto.ImportGatewayArtifactsResponse {
	ordered := make([]dto.ImportGatewayArtifactRequest, len(reqs))
	copy(ordered, reqs)
	sort.SliceStable(ordered, func(i, j int) bool {
		return utils.ArtifactImportRank(ordered[i].Configuration.Kind) < utils.ArtifactImportRank(ordered[j].Configuration.Kind)
	})

	resp := &dto.ImportGatewayArtifactsResponse{
		Total:     len(reqs),
		Artifacts: make(map[string]dto.ImportGatewayArtifactResponse, len(reqs)),
	}
	// Resolve and validate the gateway once for the whole batch; each artifact reuses it
	_, gwErr := s.getGatewayForOrg(orgID, gatewayID)
	for i := range ordered {
		req := ordered[i]
		var result *dto.ImportGatewayArtifactResponse
		err := gwErr
		if err == nil {
			result, err = s.importValidated(orgID, gatewayID, req)
		}
		if err != nil {
			s.slogger.Warn("Failed to import gateway artifact in bulk push",
				"dpid", req.DPID, "kind", req.Configuration.Kind, "gatewayId", gatewayID, "error", err)
			resp.Failed++
			resp.Artifacts[req.DPID] = dto.ImportGatewayArtifactResponse{
				Status: utils.ImportStatusFailed,
				Origin: constants.OriginDP,
				Error:  err.Error(),
			}
			continue
		}
		resp.Success++
		resp.Artifacts[req.DPID] = *result
	}
	return resp
}

// Import is the entry point for the DP->CP push. It authenticates the gateway,
// resolves the importer by kind, resolves the project when required, delegates to
// the importer, and persists deployment/status for deployable kinds.
func (s *ArtifactImportService) Import(orgID, gatewayID string, req dto.ImportGatewayArtifactRequest) (*dto.ImportGatewayArtifactResponse, error) {
	if orgID == "" || gatewayID == "" || req.DPID == "" {
		return nil, apperror.ValidationFailed.New("The organization, gateway and artifact id are required.")
	}
	// Verify the gateway exists and belongs to the org before importing.
	if _, err := s.getGatewayForOrg(orgID, gatewayID); err != nil {
		return nil, err
	}
	return s.importValidated(orgID, gatewayID, req)
}

// getGatewayForOrg resolves the gateway and verifies it belongs to the org. ImportArtifacts
// calls this once for the whole batch (and Import once per call) so the per-artifact path
// does not re-fetch the same gateway on every item.
func (s *ArtifactImportService) getGatewayForOrg(orgID, gatewayID string) (*model.Gateway, error) {
	gateway, err := s.gatewayRepo.GetByUUID(gatewayID)
	if err != nil {
		return nil, fmt.Errorf("failed to get gateway: %w", err)
	}
	if gateway == nil || gateway.OrganizationID != orgID {
		return nil, apperror.GatewayNotFound.New()
	}
	return gateway, nil
}

// importConflictMaxRetries bounds how many times importValidated re-resolves and retries a
// single artifact import after a unique-constraint violation
const importConflictMaxRetries = 3

// importValidated imports a single artifact, assuming the gateway has already been resolved
// and validated for the org (so a batch validates the gateway once instead of per artifact).
func (s *ArtifactImportService) importValidated(orgID, gatewayID string, req dto.ImportGatewayArtifactRequest) (*dto.ImportGatewayArtifactResponse, error) {
	if req.DPID == "" {
		return nil, apperror.ValidationFailed.New("The artifact id is required.")
	}
	kind := req.Configuration.Kind
	importer, ok := s.importers[kind]
	if !ok {
		s.slogger.Warn("Unsupported artifact kind for gateway import", "kind", kind, "artifactId", req.DPID)
		return nil, apperror.ValidationFailed.New(fmt.Sprintf("Unsupported artifact kind %q.", kind))
	}

	// An "undeployed" push means the artifact was deleted from the gateway. The control
	// plane keeps the artifact but marks it undeployed on this gateway — it does not
	// delete it, create a new deployment, or touch the metadata. A later "deployed"
	// push (re-deploy) takes the normal path below, creating a fresh deployment and
	// updating metadata when this push wins the last-in-wins race.
	if req.Status == utils.ImportStatusUndeployed {
		return s.handleUndeploy(orgID, gatewayID, req)
	}

	ictx := &ImportContext{
		OrgID:         orgID,
		GatewayID:     gatewayID,
		DPID:          req.DPID,
		Configuration: req.Configuration,
		Status:        req.Status,
		CreatedAt:     req.CreatedAt,
		UpdatedAt:     req.UpdatedAt,
		DeployedAt:    req.DeployedAt,
		Properties:    req.Properties,
		ProjectName:   utils.ResolveImportProject(req.Configuration.Metadata),
	}

	// Resolve project for project-scoped kinds. Org-level kinds ignore the project.
	if importer.RequiresProject() {
		if ictx.ProjectName == "" {
			// The gateway must always supply the project (as a metadata label) for
			// project-scoped kinds; a push without one is a contract violation.
			s.slogger.Error("Project is required for gateway-imported artifact but was not provided",
				"kind", kind, "artifactId", req.DPID)
			return nil, apperror.ValidationFailed.New(fmt.Sprintf("A project is required for artifact kind %q.", kind))
		}
		project, err := s.projectRepo.GetProjectByNameAndOrgID(ictx.ProjectName, orgID)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve project %q: %w", ictx.ProjectName, err)
		}
		if project == nil {
			// The project was provided but does not exist in this organization. Reject the
			// import with ErrProjectNotFound (the project is never created or defaulted);
			// the artifact is not created in the control plane.
			s.slogger.Error("Project is not available in the organization; gateway artifact not imported",
				"kind", kind, "artifactId", req.DPID, "project", ictx.ProjectName, "orgId", orgID)
			return nil, apperror.ProjectNotFound.New().WithLogMessage(
				fmt.Sprintf("project %q does not exist in org %q", ictx.ProjectName, orgID))
		}
		ictx.ProjectID = project.ID
	}

	// Resolve the existing artifact by handle, decide the last-in-wins write mode, and run the
	// per-kind importer — retrying on a unique-constraint violation to close a TOCTOU race.
	handle := utils.ImportHandle(ictx.Configuration)
	var result *ImportResult
	var err error
	for attempt := 0; ; attempt++ {
		result, err = s.resolveAndImport(importer, ictx, handle, orgID, kind, req.DeployedAt)
		if err == nil {
			break
		}
		if attempt < importConflictMaxRetries && repository.IsUniqueViolation(err) {
			s.slogger.Info("Concurrent same-handle import detected; re-resolving and retrying as update",
				"kind", kind, "handle", handle, "orgId", orgID, "attempt", attempt+1)
			continue
		}
		return nil, err
	}

	// Persist deployment + status for deployable kinds (everything except templates).
	if result.Deployable {
		if err := s.writeDeployment(ictx, result.ID); err != nil {
			return nil, err
		}
	}

	return &dto.ImportGatewayArtifactResponse{
		ID:              result.ID,
		Status:          req.Status,
		Origin:          constants.OriginDP,
		CreatedAt:       req.CreatedAt,
		UpdatedAt:       req.UpdatedAt,
		DeployedAt:      req.DeployedAt,
		DeployedVersion: result.DeployedVersion,
	}, nil
}

// resolveAndImport resolves the existing artifact by handle, computes the last-in-wins
// metadata write mode for this push, and runs the per-kind importer once.
func (s *ArtifactImportService) resolveAndImport(
	importer GatewayArtifactImporter,
	ictx *ImportContext,
	handle, orgID, kind string,
	incomingDeployedAt *time.Time,
) (*ImportResult, error) {
	// The control plane owns the artifact UUID; it does NOT reuse the data-plane UUID
	// (the gateway mints a fresh one whenever the artifact is recreated).
	existing, err := s.artifactRepo.GetByHandle(handle, orgID)
	if err != nil {
		return nil, fmt.Errorf("failed to look up existing artifact: %w", err)
	}
	if existing != nil {
		// Guard against handle reuse across kinds. GetByHandle reports the artifact kind in
		// the Type field (the artifacts.type column).
		if existing.Type != kind {
			return nil, apperror.ArtifactExists.New().WithLogMessage(
				fmt.Sprintf("artifact %q already exists with kind %s", handle, existing.Type))
		}
		ictx.ID = existing.UUID
		ictx.Existing = existing
	} else {
		ictx.ID = uuid.NewString()
		ictx.Existing = nil
	}

	// Decide the working-copy (metadata) write mode using last-in-wins by deployment time.
	var currentOrigin string
	var currentDeployedAt *time.Time
	if existing != nil {
		currentOrigin = existing.Origin
		latest, err := s.deploymentRepo.GetLatestDeploymentTime(existing.UUID, orgID)
		if err != nil {
			return nil, fmt.Errorf("failed to look up latest deployment time: %w", err)
		}
		currentDeployedAt = latest
	}
	ictx.MetadataMode = utils.DecideMetadataWrite(existing == nil, currentOrigin, currentDeployedAt, incomingDeployedAt)

	return importer.Import(ictx)
}

// writeDeployment records the immutable deployment artifact, upserts the current
// deployment_status row, and ensures the artifact<->gateway association exists.
func (s *ArtifactImportService) writeDeployment(ictx *ImportContext, artifactUUID string) error {
	content, err := yaml.Marshal(ictx.Configuration)
	if err != nil {
		return fmt.Errorf("failed to serialize deployment content: %w", err)
	}

	if s.cfg.Deployments.MaxPerAPIGateway < 1 {
		return fmt.Errorf("MaxPerAPIGateway limit config must be at least 1, got %d", s.cfg.Deployments.MaxPerAPIGateway)
	}
	hardLimit := s.cfg.Deployments.MaxPerAPIGateway + constants.DeploymentLimitBuffer

	status := utils.MapDeploymentStatus(ictx.Status)
	now := time.Now()
	// created_at is the gateway's deployment time (UTC), not CP wall-clock: it is the
	// last-in-wins watermark read back via GetLatestDeploymentTime. Fall back to now when the
	// push carries no deployment time (e.g. a pending/failed status with no deployedAt).
	createdAt := now
	if ictx.DeployedAt != nil {
		createdAt = ictx.DeployedAt.UTC()
	}
	deployment := &model.Deployment{
		Name:           fmt.Sprintf("deployment-%d", now.Unix()),
		ArtifactID:     artifactUUID,
		GatewayID:      ictx.GatewayID,
		OrganizationID: ictx.OrgID,
		Content:        content,
		Status:         &status,
		CreatedAt:      createdAt,
	}
	if err := s.deploymentRepo.CreateWithLimitEnforcement(deployment, hardLimit); err != nil {
		return fmt.Errorf("failed to create deployment record: %w", err)
	}

	// Ensure the gateway association exists so the artifact is listed against the
	// gateway in the control plane. association_mappings is generic across kinds.
	assocs, err := s.apiRepo.GetAPIAssociations(artifactUUID, constants.AssociationTypeGateway, ictx.OrgID)
	if err != nil {
		return fmt.Errorf("failed to check artifact-gateway associations: %w", err)
	}
	associated := false
	for _, a := range assocs {
		if a.GatewayID == ictx.GatewayID {
			associated = true
			break
		}
	}
	if !associated {
		now := time.Now()
		if err := s.apiRepo.CreateAPIAssociation(&model.APIAssociation{
			ArtifactID:     artifactUUID,
			OrganizationID: ictx.OrgID,
			GatewayID:      ictx.GatewayID,
			CreatedAt:      now,
			UpdatedAt:      now,
		}); err != nil {
			return fmt.Errorf("failed to create artifact-gateway association: %w", err)
		}
	}
	return nil
}

// handleUndeploy processes an "undeployed" push (the artifact was deleted from the
// gateway). It marks the artifact undeployed on this gateway and keeps it: it never
// deletes the artifact, never creates a new deployment record, and never alters the
// metadata. If the artifact (or its deployment status row) is unknown it is a no-op.
func (s *ArtifactImportService) handleUndeploy(orgID, gatewayID string, req dto.ImportGatewayArtifactRequest) (*dto.ImportGatewayArtifactResponse, error) {
	// ID is left empty here and only set to the control-plane UUID once GetByHandle resolves
	// a real existing artifact below.
	resp := &dto.ImportGatewayArtifactResponse{
		Status:     req.Status,
		Origin:     constants.OriginDP,
		CreatedAt:  req.CreatedAt,
		UpdatedAt:  req.UpdatedAt,
		DeployedAt: req.DeployedAt,
	}

	// Match by handle: the data-plane UUID is regenerated on recreate and is never the
	// CP UUID, so the stable per-org handle is the lookup key.
	handle := req.Configuration.Metadata.Name
	existing, err := s.artifactRepo.GetByHandle(handle, orgID)
	if err != nil {
		return nil, fmt.Errorf("failed to look up artifact for undeploy: %w", err)
	}
	if existing == nil {
		// Unknown artifact (e.g. an org-level template, or never imported). Nothing to
		// undeploy; the artifact is not created on an undeploy push.
		s.slogger.Warn("Undeploy push for unknown artifact; ignoring",
			"handle", handle, "dpId", req.DPID, "kind", req.Configuration.Kind, "gatewayId", gatewayID)
		return resp, nil
	}
	// Echo the control-plane UUID back to the gateway.
	resp.ID = existing.UUID
	resp.DeployedVersion = existing.Version

	deploymentID, status, _, err := s.deploymentRepo.GetStatus(existing.UUID, orgID, gatewayID)
	if err != nil {
		return nil, fmt.Errorf("failed to get deployment status for undeploy: %w", err)
	}
	if deploymentID == "" {
		s.slogger.Warn("Undeploy push but no deployment status exists for artifact on gateway; nothing to undeploy",
			"artifactId", existing.UUID, "gatewayId", gatewayID)
		return resp, nil
	}
	if status == model.DeploymentStatusUndeployed {
		return resp, nil // already undeployed; idempotent
	}
	if _, err := s.deploymentRepo.SetCurrentWithDetails(
		existing.UUID, orgID, gatewayID, deploymentID, model.DeploymentStatusUndeployed, "", nil, ""); err != nil {
		return nil, fmt.Errorf("failed to mark artifact undeployed: %w", err)
	}
	s.slogger.Info("Marked gateway-deleted artifact as undeployed in the control plane",
		"artifactId", existing.UUID, "gatewayId", gatewayID)
	return resp, nil
}
