/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

package service

import (
	"errors"
	"io"
	"log/slog"
	"strings"
	"testing"
	"time"

	"platform-api/src/internal/constants"
	"platform-api/src/internal/model"
	"platform-api/src/internal/repository"
)

// testEncKey is a valid 64-hex-char (32-byte) AES-256 key for use in tests.
const testEncKey = "aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899"

// ─── Mock HMAC Secret Repository ─────────────────────────────────────────────

type mockHmacSecretRepo struct {
	repository.WebSubAPIHmacSecretRepository
	store map[string]*model.WebSubAPIHmacSecret
}

func newMockHmacSecretRepo() *mockHmacSecretRepo {
	return &mockHmacSecretRepo{store: make(map[string]*model.WebSubAPIHmacSecret)}
}

func hmacSecretKey(artifactUUID, name string) string { return artifactUUID + ":" + name }

func (m *mockHmacSecretRepo) Create(s *model.WebSubAPIHmacSecret) error {
	key := hmacSecretKey(s.ArtifactUUID, s.Handle)
	if _, exists := m.store[key]; exists {
		return errors.New("UNIQUE constraint failed: websub_api_hmac_secrets.artifact_uuid, websub_api_hmac_secrets.handle")
	}
	s.CreatedAt = time.Now()
	s.UpdatedAt = time.Now()
	cp := *s
	m.store[key] = &cp
	return nil
}

func (m *mockHmacSecretRepo) GetByArtifactAndName(artifactUUID, name string) (*model.WebSubAPIHmacSecret, error) {
	s, ok := m.store[hmacSecretKey(artifactUUID, name)]
	if !ok {
		return nil, nil
	}
	cp := *s
	return &cp, nil
}

func (m *mockHmacSecretRepo) ListByArtifact(artifactUUID string) ([]*model.WebSubAPIHmacSecret, error) {
	prefix := artifactUUID + ":"
	var result []*model.WebSubAPIHmacSecret
	for k, v := range m.store {
		if strings.HasPrefix(k, prefix) {
			cp := *v
			result = append(result, &cp)
		}
	}
	return result, nil
}

func (m *mockHmacSecretRepo) Update(s *model.WebSubAPIHmacSecret) error {
	key := hmacSecretKey(s.ArtifactUUID, s.Handle)
	if _, ok := m.store[key]; !ok {
		return errors.New("not found")
	}
	cp := *s
	m.store[key] = &cp
	return nil
}

func (m *mockHmacSecretRepo) Delete(artifactUUID, name string) error {
	key := hmacSecretKey(artifactUUID, name)
	if _, ok := m.store[key]; !ok {
		return errors.New("not found")
	}
	delete(m.store, key)
	return nil
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// withWebSubAPI pre-populates the mock with one API so HMAC secret operations
// can find it by handle. The UUID is fixed so tests can predict store keys.
func withWebSubAPI(repo *mockWebSubAPIRepository) {
	repo.store["test-api"] = &model.WebSubAPI{
		UUID:             "art-uuid-1",
		Handle:           "test-api",
		OrganizationUUID: "org-uuid",
		ProjectUUID:      "proj-uuid",
	}
}

func buildHmacSecretService(t *testing.T, websubRepo *mockWebSubAPIRepository, hmacRepo *mockHmacSecretRepo) *WebSubAPIHmacSecretService {
	t.Helper()
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	svc, err := NewWebSubAPIHmacSecretService(hmacRepo, websubRepo, nil, nil, testEncKey, logger)
	if err != nil {
		t.Fatalf("NewWebSubAPIHmacSecretService: %v", err)
	}
	return svc
}

// ─── Generate ────────────────────────────────────────────────────────────────

// TestWebSubAPIHmacSecret_Generate_AutoGenerated verifies that Generate produces
// a plaintext in the expected whsec_ format and persists the secret metadata.
func TestWebSubAPIHmacSecret_Generate_AutoGenerated(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	meta, plaintext, err := svc.Generate("org-uuid", "test-api", "My GitHub Secret", "", "test-user")
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Plaintext format: whsec_ + 64 hex chars = 70 chars.
	if !strings.HasPrefix(plaintext, "whsec_") {
		t.Errorf("plaintext should start with 'whsec_', got %q", plaintext)
	}
	if len(plaintext) != 70 {
		t.Errorf("expected plaintext length 70, got %d", len(plaintext))
	}

	// Metadata.
	if meta == nil {
		t.Fatal("expected non-nil metadata")
	}
	if meta.Handle != "my-github-secret" {
		t.Errorf("expected slugified handle 'my-github-secret', got %q", meta.Handle)
	}
	if meta.Name != "My GitHub Secret" {
		t.Errorf("expected name 'My GitHub Secret', got %q", meta.Name)
	}
	if meta.ArtifactUUID != "art-uuid-1" {
		t.Errorf("expected artifact UUID 'art-uuid-1', got %q", meta.ArtifactUUID)
	}
	if meta.Status != "active" {
		t.Errorf("expected status 'active', got %q", meta.Status)
	}

	// Secret stored in repo with correct key.
	stored := hmacRepo.store[hmacSecretKey("art-uuid-1", "my-github-secret")]
	if stored == nil {
		t.Fatal("secret not found in repo after Generate")
	}
	// Encrypted form should differ from plaintext.
	if stored.EncryptedSecret == plaintext {
		t.Error("encrypted secret must not equal plaintext")
	}
}

// TestWebSubAPIHmacSecret_Generate_ExternalSecret verifies that a caller-supplied
// secret value is accepted when it meets the minimum-length requirement.
func TestWebSubAPIHmacSecret_Generate_ExternalSecret(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	external := strings.Repeat("x", 40) // 40 chars, well above the 32-char minimum.
	_, plaintext, err := svc.Generate("org-uuid", "test-api", "Caller Secret", external, "test-user")
	if err != nil {
		t.Fatalf("Generate with external secret failed: %v", err)
	}
	if plaintext != external {
		t.Errorf("expected returned plaintext to equal supplied secret, got %q", plaintext)
	}
}

// TestWebSubAPIHmacSecret_Generate_ShortExternalSecret verifies that a
// caller-supplied secret shorter than 32 chars is rejected.
func TestWebSubAPIHmacSecret_Generate_ShortExternalSecret(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	svc := buildHmacSecretService(t, websubRepo, newMockHmacSecretRepo())

	_, _, err := svc.Generate("org-uuid", "test-api", "Short Secret", "tooshort", "test-user")
	if !errors.Is(err, constants.ErrHmacSecretInvalidValue) {
		t.Errorf("expected ErrHmacSecretInvalidValue, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_Generate_APINotFound verifies that Generate returns
// ErrWebSubAPINotFound when the API handle does not exist.
func TestWebSubAPIHmacSecret_Generate_APINotFound(t *testing.T) {
	svc := buildHmacSecretService(t, newMockWebSubAPIRepository(), newMockHmacSecretRepo())

	_, _, err := svc.Generate("org-uuid", "nonexistent", "Secret", "", "test-user")
	if !errors.Is(err, constants.ErrWebSubAPINotFound) {
		t.Errorf("expected ErrWebSubAPINotFound, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_Generate_DuplicateName verifies that a second Generate
// with the same display name (and thus the same slug) returns ErrHmacSecretAlreadyExists.
func TestWebSubAPIHmacSecret_Generate_DuplicateName(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "deploy-key", "", "test-user"); err != nil {
		t.Fatalf("first Generate failed: %v", err)
	}
	_, _, err := svc.Generate("org-uuid", "test-api", "deploy-key", "", "test-user")
	if !errors.Is(err, constants.ErrHmacSecretAlreadyExists) {
		t.Errorf("expected ErrHmacSecretAlreadyExists on duplicate name, got %v", err)
	}
}

// ─── List ────────────────────────────────────────────────────────────────────

// TestWebSubAPIHmacSecret_List_ReturnsSecrets verifies that List returns all
// secrets previously generated for the API.
func TestWebSubAPIHmacSecret_List_ReturnsSecrets(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "Secret Alpha", "", "test-user"); err != nil {
		t.Fatalf("Generate alpha failed: %v", err)
	}
	if _, _, err := svc.Generate("org-uuid", "test-api", "Secret Beta", "", "test-user"); err != nil {
		t.Fatalf("Generate beta failed: %v", err)
	}

	list, err := svc.List("org-uuid", "test-api")
	if err != nil {
		t.Fatalf("List failed: %v", err)
	}
	if len(list) != 2 {
		t.Errorf("expected 2 secrets, got %d", len(list))
	}
	// Encrypted secret must not be the empty string.
	for _, s := range list {
		if s.EncryptedSecret == "" {
			t.Errorf("secret %q has empty EncryptedSecret", s.Handle)
		}
	}
}

// TestWebSubAPIHmacSecret_List_APINotFound verifies that List returns
// ErrWebSubAPINotFound for an unknown API handle.
func TestWebSubAPIHmacSecret_List_APINotFound(t *testing.T) {
	svc := buildHmacSecretService(t, newMockWebSubAPIRepository(), newMockHmacSecretRepo())

	_, err := svc.List("org-uuid", "no-such-api")
	if !errors.Is(err, constants.ErrWebSubAPINotFound) {
		t.Errorf("expected ErrWebSubAPINotFound, got %v", err)
	}
}

// ─── Regenerate ──────────────────────────────────────────────────────────────

// TestWebSubAPIHmacSecret_Regenerate_ReplacesValue verifies that Regenerate
// produces a new plaintext value and updates the stored ciphertext.
func TestWebSubAPIHmacSecret_Regenerate_ReplacesValue(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "Webhook Key", "", "test-user"); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	originalCiphertext := hmacRepo.store[hmacSecretKey("art-uuid-1", "webhook-key")].EncryptedSecret

	_, newPlaintext, err := svc.Regenerate("org-uuid", "test-api", "webhook-key", "", "test-user")
	if err != nil {
		t.Fatalf("Regenerate failed: %v", err)
	}

	if !strings.HasPrefix(newPlaintext, "whsec_") {
		t.Errorf("regenerated plaintext should start with 'whsec_', got %q", newPlaintext)
	}
	if len(newPlaintext) != 70 {
		t.Errorf("expected regenerated plaintext length 70, got %d", len(newPlaintext))
	}

	updatedCiphertext := hmacRepo.store[hmacSecretKey("art-uuid-1", "webhook-key")].EncryptedSecret
	if updatedCiphertext == originalCiphertext {
		t.Error("ciphertext should change after Regenerate")
	}
}

// TestWebSubAPIHmacSecret_Regenerate_ExternalSecret verifies that Regenerate
// accepts and stores a caller-supplied secret value.
func TestWebSubAPIHmacSecret_Regenerate_ExternalSecret(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "deploy key", "", "test-user"); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	newExternal := strings.Repeat("z", 40)
	_, plaintext, err := svc.Regenerate("org-uuid", "test-api", "deploy-key", newExternal, "test-user")
	if err != nil {
		t.Fatalf("Regenerate with external secret failed: %v", err)
	}
	if plaintext != newExternal {
		t.Errorf("expected returned plaintext %q, got %q", newExternal, plaintext)
	}
}

// TestWebSubAPIHmacSecret_Regenerate_ShortExternalSecret verifies that Regenerate
// rejects a caller-supplied secret shorter than 32 chars.
func TestWebSubAPIHmacSecret_Regenerate_ShortExternalSecret(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "webhook key", "", "test-user"); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	_, _, err := svc.Regenerate("org-uuid", "test-api", "webhook-key", "short", "test-user")
	if !errors.Is(err, constants.ErrHmacSecretInvalidValue) {
		t.Errorf("expected ErrHmacSecretInvalidValue, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_Regenerate_APINotFound verifies that Regenerate returns
// ErrWebSubAPINotFound when the API handle does not exist.
func TestWebSubAPIHmacSecret_Regenerate_APINotFound(t *testing.T) {
	svc := buildHmacSecretService(t, newMockWebSubAPIRepository(), newMockHmacSecretRepo())

	_, _, err := svc.Regenerate("org-uuid", "nonexistent", "my-secret", "", "test-user")
	if !errors.Is(err, constants.ErrWebSubAPINotFound) {
		t.Errorf("expected ErrWebSubAPINotFound, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_Regenerate_SecretNotFound verifies that Regenerate
// returns ErrHmacSecretNotFound for an unknown secret name.
func TestWebSubAPIHmacSecret_Regenerate_SecretNotFound(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	svc := buildHmacSecretService(t, websubRepo, newMockHmacSecretRepo())

	_, _, err := svc.Regenerate("org-uuid", "test-api", "no-such-secret", "", "test-user")
	if !errors.Is(err, constants.ErrHmacSecretNotFound) {
		t.Errorf("expected ErrHmacSecretNotFound, got %v", err)
	}
}

// ─── Delete ──────────────────────────────────────────────────────────────────

// TestWebSubAPIHmacSecret_Delete_Removes verifies that Delete removes the named
// secret from the repository.
func TestWebSubAPIHmacSecret_Delete_Removes(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	if _, _, err := svc.Generate("org-uuid", "test-api", "Deploy Key", "", "test-user"); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if err := svc.Delete("org-uuid", "test-api", "deploy-key"); err != nil {
		t.Fatalf("Delete failed: %v", err)
	}

	if _, ok := hmacRepo.store[hmacSecretKey("art-uuid-1", "deploy-key")]; ok {
		t.Error("secret should not exist in repo after Delete")
	}
}

// TestWebSubAPIHmacSecret_Delete_APINotFound verifies that Delete returns
// ErrWebSubAPINotFound when the API handle does not exist.
func TestWebSubAPIHmacSecret_Delete_APINotFound(t *testing.T) {
	svc := buildHmacSecretService(t, newMockWebSubAPIRepository(), newMockHmacSecretRepo())

	err := svc.Delete("org-uuid", "nonexistent", "my-secret")
	if !errors.Is(err, constants.ErrWebSubAPINotFound) {
		t.Errorf("expected ErrWebSubAPINotFound, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_Delete_SecretNotFound verifies that Delete returns
// ErrHmacSecretNotFound when the named secret does not exist.
func TestWebSubAPIHmacSecret_Delete_SecretNotFound(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	svc := buildHmacSecretService(t, websubRepo, newMockHmacSecretRepo())

	err := svc.Delete("org-uuid", "test-api", "no-such-secret")
	if !errors.Is(err, constants.ErrHmacSecretNotFound) {
		t.Errorf("expected ErrHmacSecretNotFound, got %v", err)
	}
}

// ─── Helper functions ─────────────────────────────────────────────────────────

// TestSlugifyHmacSecret verifies the slug conversion used to derive secret names
// from human-readable display names.
func TestSlugifyHmacSecret(t *testing.T) {
	cases := []struct {
		input string
		want  string
	}{
		{"My GitHub Secret", "my-github-secret"},
		{"  leading and trailing  ", "leading-and-trailing"},
		{"hello_world", "hello-world"},
		{"UPPER CASE", "upper-case"},
		{"already-slugified", "already-slugified"},
		{"mixed  spaces   and__underscores", "mixed--spaces---and--underscores"},
		{"special!@#chars", "specialchars"},
		{"", ""},
		{"123numeric456", "123numeric456"},
	}
	for _, tc := range cases {
		got := slugifyHmacSecret(tc.input)
		if got != tc.want {
			t.Errorf("slugifyHmacSecret(%q) = %q, want %q", tc.input, got, tc.want)
		}
	}
}

// TestWebSubAPIHmacSecret_ConstructorRejectsEmptyKey verifies that
// NewWebSubAPIHmacSecretService returns an error when no encryption key is provided.
func TestWebSubAPIHmacSecret_ConstructorRejectsEmptyKey(t *testing.T) {
	_, err := NewWebSubAPIHmacSecretService(
		newMockHmacSecretRepo(),
		newMockWebSubAPIRepository(),
		nil, nil,
		"",
		slog.New(slog.NewTextHandler(io.Discard, nil)),
	)
	if !errors.Is(err, constants.ErrHmacSecretEncryptionKeyMissing) {
		t.Errorf("expected ErrHmacSecretEncryptionKeyMissing, got %v", err)
	}
}

// TestWebSubAPIHmacSecret_DecryptSecret verifies the round-trip: a generated
// secret can be decrypted back to the original plaintext via DecryptSecret.
func TestWebSubAPIHmacSecret_DecryptSecret(t *testing.T) {
	websubRepo := newMockWebSubAPIRepository()
	withWebSubAPI(websubRepo)
	hmacRepo := newMockHmacSecretRepo()
	svc := buildHmacSecretService(t, websubRepo, hmacRepo)

	_, plaintext, err := svc.Generate("org-uuid", "test-api", "Round Trip", "", "test-user")
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	stored := hmacRepo.store[hmacSecretKey("art-uuid-1", "round-trip")]
	if stored == nil {
		t.Fatal("secret not in repo after Generate")
	}

	decrypted, err := svc.DecryptSecret(stored)
	if err != nil {
		t.Fatalf("DecryptSecret failed: %v", err)
	}
	if decrypted != plaintext {
		t.Errorf("DecryptSecret round-trip: want %q, got %q", plaintext, decrypted)
	}
}
