# --------------------------------------------------------------------
# Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# --------------------------------------------------------------------

apiVersion: gateway.api-platform.wso2.com/v1
kind: GraphQLApi
metadata:
  name: countries-graphql-v1
  annotations:
    gateway.api-platform.wso2.com/project-id: default-project
spec:
  displayName: Countries
  version: v1
  context: /countries/$version/graphql
  upstream:
    main:
      url: https://countries.trevorblades.com/graphql
  policies:
    - name: jwt-auth
      version: v1
      params:
        issuers: [PrimaryIdp]
        scopes:
          anyOf: ["graphql:read", "graphql:write"]
