# --------------------------------------------------------------------
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# --------------------------------------------------------------------

apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: Mcp
metadata:
  name: everything-mcp-v1.0
spec:
  displayName: Everything
  version: v1.0
  context: /everything
  specVersion: "2025-06-18"
  # vhost: "mcp1.api-platform.com"
  upstream:
    url: http://everything:3001
    # auth:
    #   type: api-key
    #   header: x-api-key
    #   value: 12345
  # policies:
  #   - name: mcp-auth
  #     version: v1
  #     params:
  #       issuers:
  #         - PrimaryIdp
  #   - name: mcp-authz
  #     version: v1
  #     params:
  #       tools:
  #         - name: "viewPizzaMenu"
  #           requiredScopes:
  #             - "mcp:tools:invoke"
  #         - name: "echo"
  #           requiredScopes:
  #             - "mcp:tools:invoke"
  #       prompts:
  #         - name: "complex_prompt"
  #           requiredClaims:
  #             sub: "harry@gmail.com"
  #   - name: mcp-acl-list
  #     version: v1
  #     params:
  #       tools:
  #         mode: deny
  #         exceptions:
  #           - viewPizzaMenu
  #           - echo
