# --------------------------------------------------------------------
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# --------------------------------------------------------------------

apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: RestApi
metadata:
  name: weather-api-v1.0
spec:
  displayName: Weather-API
  version: v1.0
  context: /weather/$version
  upstream:
    main:
      url: http://sample-backend:5000/api/v2
  policies:
    - name: modify-headers
      version: v0
      params:
        requestHeaders:
          - action: SET
            name: api-level-req-header
            value: hello
        responseHeaders:
          - action: SET
            name: api-level-res-header
            value: world
          - action: SET
            name: x-content-type-options
            value: nosniff
  operations:
    - method: GET
      path: /{country_code}/{city}
      policies:
        - name: modify-headers
          version: v0
          params:
            requestHeaders:
              - action: SET
                name: operation-level-req-header
                value: hello
            responseHeaders:
              - action: SET
                name: operation-level-res-header
                value: world
        - name: basic-ratelimit
          version: v0
          params:
            limits:
              - limit: 5
                duration: "1m"
    - method: GET
      path: /alerts/active
    - method: POST
      path: /alerts/active
      policies:
        - name: respond
          version: v0
          params:
            statusCode: 201
            body: '{"message": "Active weather alert created successfully."}'
            headers:
              - name: Content-Type
                value: application/json
