apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: WebSubApi
metaData:
   name: WebSubHub-API
spec:
  displayName: WebSub-API-New-API
  version: v1.0
  context: /websubnewapi
  vhosts:
    main: "*"
  channels:
    -  path: /pull-requests
       subscribe:
        policies:
          - name: ModifyHeaders
            version: v1.0.0
            enabled: true
            params:
              requestHeaders:
                - action: SET
                  name: operation-level-req-header
                  value: hello
              responseHeaders:
                - action: SET
                  name: operation-level-res-header
                  value: world
    -  path: /issues
       subscribe:
         policies:
          - name: ModifyHeaders
            version: v1.0.0
            enabled: true
            params:
              requestHeaders:
                - action: SET
                  name: operation-level-req-header
                  value: hello
              responseHeaders:
                - action: SET
                  name: operation-level-res-header
                  value: world