//
//  Copyright (c) 2025, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: python_executor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PythonExecutorService_ExecuteStream_FullMethodName = "/wso2.gateway.python.v1alpha2.PythonExecutorService/ExecuteStream"
	PythonExecutorService_HealthCheck_FullMethodName   = "/wso2.gateway.python.v1alpha2.PythonExecutorService/HealthCheck"
	PythonExecutorService_InitPolicy_FullMethodName    = "/wso2.gateway.python.v1alpha2.PythonExecutorService/InitPolicy"
	PythonExecutorService_DestroyPolicy_FullMethodName = "/wso2.gateway.python.v1alpha2.PythonExecutorService/DestroyPolicy"
)

// PythonExecutorServiceClient is the client API for PythonExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PythonExecutorService defines the gRPC contract between the Go policy engine
// and the Python executor process.
type PythonExecutorServiceClient interface {
	// Bidirectional stream for all hot-path execution requests.
	ExecuteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error)
	// Unary lifecycle and health RPCs.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	InitPolicy(ctx context.Context, in *InitPolicyRequest, opts ...grpc.CallOption) (*InitPolicyResponse, error)
	DestroyPolicy(ctx context.Context, in *DestroyPolicyRequest, opts ...grpc.CallOption) (*DestroyPolicyResponse, error)
}

type pythonExecutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPythonExecutorServiceClient(cc grpc.ClientConnInterface) PythonExecutorServiceClient {
	return &pythonExecutorServiceClient{cc}
}

func (c *pythonExecutorServiceClient) ExecuteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PythonExecutorService_ServiceDesc.Streams[0], PythonExecutorService_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PythonExecutorService_ExecuteStreamClient = grpc.BidiStreamingClient[StreamRequest, StreamResponse]

func (c *pythonExecutorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PythonExecutorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonExecutorServiceClient) InitPolicy(ctx context.Context, in *InitPolicyRequest, opts ...grpc.CallOption) (*InitPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitPolicyResponse)
	err := c.cc.Invoke(ctx, PythonExecutorService_InitPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pythonExecutorServiceClient) DestroyPolicy(ctx context.Context, in *DestroyPolicyRequest, opts ...grpc.CallOption) (*DestroyPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyPolicyResponse)
	err := c.cc.Invoke(ctx, PythonExecutorService_DestroyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PythonExecutorServiceServer is the server API for PythonExecutorService service.
// All implementations must embed UnimplementedPythonExecutorServiceServer
// for forward compatibility.
//
// PythonExecutorService defines the gRPC contract between the Go policy engine
// and the Python executor process.
type PythonExecutorServiceServer interface {
	// Bidirectional stream for all hot-path execution requests.
	ExecuteStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error
	// Unary lifecycle and health RPCs.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	InitPolicy(context.Context, *InitPolicyRequest) (*InitPolicyResponse, error)
	DestroyPolicy(context.Context, *DestroyPolicyRequest) (*DestroyPolicyResponse, error)
	mustEmbedUnimplementedPythonExecutorServiceServer()
}

// UnimplementedPythonExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPythonExecutorServiceServer struct{}

func (UnimplementedPythonExecutorServiceServer) ExecuteStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedPythonExecutorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPythonExecutorServiceServer) InitPolicy(context.Context, *InitPolicyRequest) (*InitPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitPolicy not implemented")
}
func (UnimplementedPythonExecutorServiceServer) DestroyPolicy(context.Context, *DestroyPolicyRequest) (*DestroyPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyPolicy not implemented")
}
func (UnimplementedPythonExecutorServiceServer) mustEmbedUnimplementedPythonExecutorServiceServer() {}
func (UnimplementedPythonExecutorServiceServer) testEmbeddedByValue()                               {}

// UnsafePythonExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PythonExecutorServiceServer will
// result in compilation errors.
type UnsafePythonExecutorServiceServer interface {
	mustEmbedUnimplementedPythonExecutorServiceServer()
}

func RegisterPythonExecutorServiceServer(s grpc.ServiceRegistrar, srv PythonExecutorServiceServer) {
	// If the following call panics, it indicates UnimplementedPythonExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PythonExecutorService_ServiceDesc, srv)
}

func _PythonExecutorService_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PythonExecutorServiceServer).ExecuteStream(&grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PythonExecutorService_ExecuteStreamServer = grpc.BidiStreamingServer[StreamRequest, StreamResponse]

func _PythonExecutorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonExecutorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonExecutorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonExecutorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonExecutorService_InitPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonExecutorServiceServer).InitPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonExecutorService_InitPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonExecutorServiceServer).InitPolicy(ctx, req.(*InitPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PythonExecutorService_DestroyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonExecutorServiceServer).DestroyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonExecutorService_DestroyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonExecutorServiceServer).DestroyPolicy(ctx, req.(*DestroyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PythonExecutorService_ServiceDesc is the grpc.ServiceDesc for PythonExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PythonExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wso2.gateway.python.v1alpha2.PythonExecutorService",
	HandlerType: (*PythonExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PythonExecutorService_HealthCheck_Handler,
		},
		{
			MethodName: "InitPolicy",
			Handler:    _PythonExecutorService_InitPolicy_Handler,
		},
		{
			MethodName: "DestroyPolicy",
			Handler:    _PythonExecutorService_DestroyPolicy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _PythonExecutorService_ExecuteStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "python_executor.proto",
}
