//
//  Copyright (c) 2025, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: python_executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID per call so responses can be correlated on the single stream.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Policy to execute (name:version format used for cache lookup, e.g., "my-policy:v1")
	PolicyName    string `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyVersion string `protobuf:"bytes,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Phase: "on_request" or "on_response"
	Phase string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	// Merged parameters (system + user) for this policy instance.
	// The Go side resolves ${config} references in systemParameters and merges
	// them with user parameters before sending. Python never sees raw ${config} strings.
	Params *structpb.Struct `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	// The request or response context data
	//
	// Types that are valid to be assigned to Context:
	//
	//	*ExecutionRequest_RequestContext
	//	*ExecutionRequest_ResponseContext
	Context isExecutionRequest_Context `protobuf_oneof:"context"`
	// Shared context (metadata, API info, auth context)
	SharedContext *SharedContext `protobuf:"bytes,8,opt,name=shared_context,json=sharedContext,proto3" json:"shared_context,omitempty"`
	// Policy metadata (route info, API info) for factory creation
	PolicyMetadata *PolicyMetadata `protobuf:"bytes,9,opt,name=policy_metadata,json=policyMetadata,proto3" json:"policy_metadata,omitempty"`
	// Instance ID assigned by Python during InitPolicy. Used to dispatch requests
	// to the correct policy instance.
	InstanceId    string `protobuf:"bytes,10,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_python_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *ExecutionRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *ExecutionRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ExecutionRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecutionRequest) GetContext() isExecutionRequest_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecutionRequest) GetRequestContext() *RequestContext {
	if x != nil {
		if x, ok := x.Context.(*ExecutionRequest_RequestContext); ok {
			return x.RequestContext
		}
	}
	return nil
}

func (x *ExecutionRequest) GetResponseContext() *ResponseContext {
	if x != nil {
		if x, ok := x.Context.(*ExecutionRequest_ResponseContext); ok {
			return x.ResponseContext
		}
	}
	return nil
}

func (x *ExecutionRequest) GetSharedContext() *SharedContext {
	if x != nil {
		return x.SharedContext
	}
	return nil
}

func (x *ExecutionRequest) GetPolicyMetadata() *PolicyMetadata {
	if x != nil {
		return x.PolicyMetadata
	}
	return nil
}

func (x *ExecutionRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type isExecutionRequest_Context interface {
	isExecutionRequest_Context()
}

type ExecutionRequest_RequestContext struct {
	RequestContext *RequestContext `protobuf:"bytes,6,opt,name=request_context,json=requestContext,proto3,oneof"`
}

type ExecutionRequest_ResponseContext struct {
	ResponseContext *ResponseContext `protobuf:"bytes,7,opt,name=response_context,json=responseContext,proto3,oneof"`
}

func (*ExecutionRequest_RequestContext) isExecutionRequest_Context() {}

func (*ExecutionRequest_ResponseContext) isExecutionRequest_Context() {}

type ExecutionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match request_id from the corresponding ExecutionRequest
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecutionResponse_RequestResult
	//	*ExecutionResponse_ResponseResult
	//	*ExecutionResponse_Error
	Result isExecutionResponse_Result `protobuf_oneof:"result"`
	// Updated shared metadata (Python may have mutated it).
	// Go side merges this back into the SharedContext.
	UpdatedMetadata *structpb.Struct `protobuf:"bytes,5,opt,name=updated_metadata,json=updatedMetadata,proto3" json:"updated_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_python_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionResponse) GetResult() isExecutionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionResponse) GetRequestResult() *RequestActionResult {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResponse_RequestResult); ok {
			return x.RequestResult
		}
	}
	return nil
}

func (x *ExecutionResponse) GetResponseResult() *ResponseActionResult {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResponse_ResponseResult); ok {
			return x.ResponseResult
		}
	}
	return nil
}

func (x *ExecutionResponse) GetError() *ExecutionError {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecutionResponse) GetUpdatedMetadata() *structpb.Struct {
	if x != nil {
		return x.UpdatedMetadata
	}
	return nil
}

type isExecutionResponse_Result interface {
	isExecutionResponse_Result()
}

type ExecutionResponse_RequestResult struct {
	RequestResult *RequestActionResult `protobuf:"bytes,2,opt,name=request_result,json=requestResult,proto3,oneof"`
}

type ExecutionResponse_ResponseResult struct {
	ResponseResult *ResponseActionResult `protobuf:"bytes,3,opt,name=response_result,json=responseResult,proto3,oneof"`
}

type ExecutionResponse_Error struct {
	Error *ExecutionError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ExecutionResponse_RequestResult) isExecutionResponse_Result() {}

func (*ExecutionResponse_ResponseResult) isExecutionResponse_Result() {}

func (*ExecutionResponse_Error) isExecutionResponse_Result() {}

// ProcessingMode declares which phases the Gateway kernel must buffer
// before calling Python policy hooks.
type ProcessingMode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "SKIP" or "PROCESS"
	RequestHeaderMode string `protobuf:"bytes,1,opt,name=request_header_mode,json=requestHeaderMode,proto3" json:"request_header_mode,omitempty"`
	// "SKIP" or "BUFFER"
	RequestBodyMode string `protobuf:"bytes,2,opt,name=request_body_mode,json=requestBodyMode,proto3" json:"request_body_mode,omitempty"`
	// "SKIP" or "PROCESS"
	ResponseHeaderMode string `protobuf:"bytes,3,opt,name=response_header_mode,json=responseHeaderMode,proto3" json:"response_header_mode,omitempty"`
	// "SKIP" or "BUFFER"
	ResponseBodyMode string `protobuf:"bytes,4,opt,name=response_body_mode,json=responseBodyMode,proto3" json:"response_body_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessingMode) Reset() {
	*x = ProcessingMode{}
	mi := &file_python_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingMode) ProtoMessage() {}

func (x *ProcessingMode) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingMode.ProtoReflect.Descriptor instead.
func (*ProcessingMode) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingMode) GetRequestHeaderMode() string {
	if x != nil {
		return x.RequestHeaderMode
	}
	return ""
}

func (x *ProcessingMode) GetRequestBodyMode() string {
	if x != nil {
		return x.RequestBodyMode
	}
	return ""
}

func (x *ProcessingMode) GetResponseHeaderMode() string {
	if x != nil {
		return x.ResponseHeaderMode
	}
	return ""
}

func (x *ProcessingMode) GetResponseBodyMode() string {
	if x != nil {
		return x.ResponseBodyMode
	}
	return ""
}

type InitPolicyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PolicyName     string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyVersion  string                 `protobuf:"bytes,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyMetadata *PolicyMetadata        `protobuf:"bytes,3,opt,name=policy_metadata,json=policyMetadata,proto3" json:"policy_metadata,omitempty"`
	Params         *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // Merged system + user params
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitPolicyRequest) Reset() {
	*x = InitPolicyRequest{}
	mi := &file_python_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPolicyRequest) ProtoMessage() {}

func (x *InitPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPolicyRequest.ProtoReflect.Descriptor instead.
func (*InitPolicyRequest) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{3}
}

func (x *InitPolicyRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *InitPolicyRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *InitPolicyRequest) GetPolicyMetadata() *PolicyMetadata {
	if x != nil {
		return x.PolicyMetadata
	}
	return nil
}

func (x *InitPolicyRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type InitPolicyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`             // Opaque ID for this instance (UUID)
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // Set if success=false
	ProcessingMode *ProcessingMode        `protobuf:"bytes,4,opt,name=processing_mode,json=processingMode,proto3" json:"processing_mode,omitempty"` // Processing requirements for this policy instance
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitPolicyResponse) Reset() {
	*x = InitPolicyResponse{}
	mi := &file_python_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPolicyResponse) ProtoMessage() {}

func (x *InitPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPolicyResponse.ProtoReflect.Descriptor instead.
func (*InitPolicyResponse) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{4}
}

func (x *InitPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitPolicyResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InitPolicyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InitPolicyResponse) GetProcessingMode() *ProcessingMode {
	if x != nil {
		return x.ProcessingMode
	}
	return nil
}

type DestroyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance to destroy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyPolicyRequest) Reset() {
	*x = DestroyPolicyRequest{}
	mi := &file_python_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyPolicyRequest) ProtoMessage() {}

func (x *DestroyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyPolicyRequest.ProtoReflect.Descriptor instead.
func (*DestroyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{5}
}

func (x *DestroyPolicyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DestroyPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyPolicyResponse) Reset() {
	*x = DestroyPolicyResponse{}
	mi := &file_python_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyPolicyResponse) ProtoMessage() {}

func (x *DestroyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyPolicyResponse.ProtoReflect.Descriptor instead.
func (*DestroyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyPolicyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SharedContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // Inter-policy communication map
	ApiId         string                 `protobuf:"bytes,4,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	ApiName       string                 `protobuf:"bytes,5,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	ApiKind       string                 `protobuf:"bytes,7,opt,name=api_kind,json=apiKind,proto3" json:"api_kind,omitempty"`
	ApiContext    string                 `protobuf:"bytes,8,opt,name=api_context,json=apiContext,proto3" json:"api_context,omitempty"`
	OperationPath string                 `protobuf:"bytes,9,opt,name=operation_path,json=operationPath,proto3" json:"operation_path,omitempty"`
	AuthContext   map[string]string      `protobuf:"bytes,10,rep,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedContext) Reset() {
	*x = SharedContext{}
	mi := &file_python_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedContext) ProtoMessage() {}

func (x *SharedContext) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedContext.ProtoReflect.Descriptor instead.
func (*SharedContext) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{7}
}

func (x *SharedContext) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SharedContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SharedContext) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SharedContext) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

func (x *SharedContext) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *SharedContext) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SharedContext) GetApiKind() string {
	if x != nil {
		return x.ApiKind
	}
	return ""
}

func (x *SharedContext) GetApiContext() string {
	if x != nil {
		return x.ApiContext
	}
	return ""
}

func (x *SharedContext) GetOperationPath() string {
	if x != nil {
		return x.OperationPath
	}
	return ""
}

func (x *SharedContext) GetAuthContext() map[string]string {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	BodyPresent   bool                   `protobuf:"varint,3,opt,name=body_present,json=bodyPresent,proto3" json:"body_present,omitempty"`
	EndOfStream   bool                   `protobuf:"varint,4,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Authority     string                 `protobuf:"bytes,7,opt,name=authority,proto3" json:"authority,omitempty"`
	Scheme        string                 `protobuf:"bytes,8,opt,name=scheme,proto3" json:"scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_python_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{8}
}

func (x *RequestContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestContext) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestContext) GetBodyPresent() bool {
	if x != nil {
		return x.BodyPresent
	}
	return false
}

func (x *RequestContext) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *RequestContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestContext) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *RequestContext) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

type ResponseContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original request data (immutable)
	RequestHeaders map[string]string `protobuf:"bytes,1,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestBody    []byte            `protobuf:"bytes,2,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	RequestPath    string            `protobuf:"bytes,3,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	RequestMethod  string            `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	// Response data
	ResponseHeaders     map[string]string `protobuf:"bytes,5,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseBody        []byte            `protobuf:"bytes,6,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseBodyPresent bool              `protobuf:"varint,7,opt,name=response_body_present,json=responseBodyPresent,proto3" json:"response_body_present,omitempty"`
	ResponseStatus      int32             `protobuf:"varint,8,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResponseContext) Reset() {
	*x = ResponseContext{}
	mi := &file_python_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseContext) ProtoMessage() {}

func (x *ResponseContext) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseContext.ProtoReflect.Descriptor instead.
func (*ResponseContext) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseContext) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *ResponseContext) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *ResponseContext) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *ResponseContext) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *ResponseContext) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *ResponseContext) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *ResponseContext) GetResponseBodyPresent() bool {
	if x != nil {
		return x.ResponseBodyPresent
	}
	return false
}

func (x *ResponseContext) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

type PolicyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteName     string                 `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	ApiId         string                 `protobuf:"bytes,2,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	ApiName       string                 `protobuf:"bytes,3,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	AttachedTo    string                 `protobuf:"bytes,5,opt,name=attached_to,json=attachedTo,proto3" json:"attached_to,omitempty"` // "api" or "route"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyMetadata) Reset() {
	*x = PolicyMetadata{}
	mi := &file_python_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyMetadata) ProtoMessage() {}

func (x *PolicyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyMetadata.ProtoReflect.Descriptor instead.
func (*PolicyMetadata) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyMetadata) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *PolicyMetadata) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

func (x *PolicyMetadata) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *PolicyMetadata) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PolicyMetadata) GetAttachedTo() string {
	if x != nil {
		return x.AttachedTo
	}
	return ""
}

type RequestActionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*RequestActionResult_ContinueRequest
	//	*RequestActionResult_ImmediateResponse
	Action        isRequestActionResult_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestActionResult) Reset() {
	*x = RequestActionResult{}
	mi := &file_python_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestActionResult) ProtoMessage() {}

func (x *RequestActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestActionResult.ProtoReflect.Descriptor instead.
func (*RequestActionResult) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{11}
}

func (x *RequestActionResult) GetAction() isRequestActionResult_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RequestActionResult) GetContinueRequest() *UpstreamRequestModifications {
	if x != nil {
		if x, ok := x.Action.(*RequestActionResult_ContinueRequest); ok {
			return x.ContinueRequest
		}
	}
	return nil
}

func (x *RequestActionResult) GetImmediateResponse() *ImmediateResponseAction {
	if x != nil {
		if x, ok := x.Action.(*RequestActionResult_ImmediateResponse); ok {
			return x.ImmediateResponse
		}
	}
	return nil
}

type isRequestActionResult_Action interface {
	isRequestActionResult_Action()
}

type RequestActionResult_ContinueRequest struct {
	ContinueRequest *UpstreamRequestModifications `protobuf:"bytes,1,opt,name=continue_request,json=continueRequest,proto3,oneof"`
}

type RequestActionResult_ImmediateResponse struct {
	ImmediateResponse *ImmediateResponseAction `protobuf:"bytes,2,opt,name=immediate_response,json=immediateResponse,proto3,oneof"`
}

func (*RequestActionResult_ContinueRequest) isRequestActionResult_Action() {}

func (*RequestActionResult_ImmediateResponse) isRequestActionResult_Action() {}

type ResponseActionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ResponseActionResult_ContinueResponse
	Action        isResponseActionResult_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseActionResult) Reset() {
	*x = ResponseActionResult{}
	mi := &file_python_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseActionResult) ProtoMessage() {}

func (x *ResponseActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseActionResult.ProtoReflect.Descriptor instead.
func (*ResponseActionResult) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseActionResult) GetAction() isResponseActionResult_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ResponseActionResult) GetContinueResponse() *UpstreamResponseModifications {
	if x != nil {
		if x, ok := x.Action.(*ResponseActionResult_ContinueResponse); ok {
			return x.ContinueResponse
		}
	}
	return nil
}

type isResponseActionResult_Action interface {
	isResponseActionResult_Action()
}

type ResponseActionResult_ContinueResponse struct {
	ContinueResponse *UpstreamResponseModifications `protobuf:"bytes,1,opt,name=continue_response,json=continueResponse,proto3,oneof"`
}

func (*ResponseActionResult_ContinueResponse) isResponseActionResult_Action() {}

type UpstreamRequestModifications struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SetHeaders        map[string]string      `protobuf:"bytes,1,rep,name=set_headers,json=setHeaders,proto3" json:"set_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoveHeaders     []string               `protobuf:"bytes,2,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	AppendHeaders     map[string]*StringList `protobuf:"bytes,3,rep,name=append_headers,json=appendHeaders,proto3" json:"append_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body              []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	BodyPresent       bool                   `protobuf:"varint,5,opt,name=body_present,json=bodyPresent,proto3" json:"body_present,omitempty"` // false means no body change, true means use body field (even if empty)
	Path              string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	PathPresent       bool                   `protobuf:"varint,7,opt,name=path_present,json=pathPresent,proto3" json:"path_present,omitempty"`
	Method            string                 `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	MethodPresent     bool                   `protobuf:"varint,9,opt,name=method_present,json=methodPresent,proto3" json:"method_present,omitempty"`
	AnalyticsMetadata *structpb.Struct       `protobuf:"bytes,10,opt,name=analytics_metadata,json=analyticsMetadata,proto3" json:"analytics_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpstreamRequestModifications) Reset() {
	*x = UpstreamRequestModifications{}
	mi := &file_python_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamRequestModifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamRequestModifications) ProtoMessage() {}

func (x *UpstreamRequestModifications) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamRequestModifications.ProtoReflect.Descriptor instead.
func (*UpstreamRequestModifications) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{13}
}

func (x *UpstreamRequestModifications) GetSetHeaders() map[string]string {
	if x != nil {
		return x.SetHeaders
	}
	return nil
}

func (x *UpstreamRequestModifications) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *UpstreamRequestModifications) GetAppendHeaders() map[string]*StringList {
	if x != nil {
		return x.AppendHeaders
	}
	return nil
}

func (x *UpstreamRequestModifications) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *UpstreamRequestModifications) GetBodyPresent() bool {
	if x != nil {
		return x.BodyPresent
	}
	return false
}

func (x *UpstreamRequestModifications) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpstreamRequestModifications) GetPathPresent() bool {
	if x != nil {
		return x.PathPresent
	}
	return false
}

func (x *UpstreamRequestModifications) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpstreamRequestModifications) GetMethodPresent() bool {
	if x != nil {
		return x.MethodPresent
	}
	return false
}

func (x *UpstreamRequestModifications) GetAnalyticsMetadata() *structpb.Struct {
	if x != nil {
		return x.AnalyticsMetadata
	}
	return nil
}

type UpstreamResponseModifications struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SetHeaders        map[string]string      `protobuf:"bytes,1,rep,name=set_headers,json=setHeaders,proto3" json:"set_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoveHeaders     []string               `protobuf:"bytes,2,rep,name=remove_headers,json=removeHeaders,proto3" json:"remove_headers,omitempty"`
	AppendHeaders     map[string]*StringList `protobuf:"bytes,3,rep,name=append_headers,json=appendHeaders,proto3" json:"append_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body              []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	BodyPresent       bool                   `protobuf:"varint,5,opt,name=body_present,json=bodyPresent,proto3" json:"body_present,omitempty"`
	StatusCode        int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusCodePresent bool                   `protobuf:"varint,7,opt,name=status_code_present,json=statusCodePresent,proto3" json:"status_code_present,omitempty"`
	AnalyticsMetadata *structpb.Struct       `protobuf:"bytes,8,opt,name=analytics_metadata,json=analyticsMetadata,proto3" json:"analytics_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpstreamResponseModifications) Reset() {
	*x = UpstreamResponseModifications{}
	mi := &file_python_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamResponseModifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamResponseModifications) ProtoMessage() {}

func (x *UpstreamResponseModifications) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamResponseModifications.ProtoReflect.Descriptor instead.
func (*UpstreamResponseModifications) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{14}
}

func (x *UpstreamResponseModifications) GetSetHeaders() map[string]string {
	if x != nil {
		return x.SetHeaders
	}
	return nil
}

func (x *UpstreamResponseModifications) GetRemoveHeaders() []string {
	if x != nil {
		return x.RemoveHeaders
	}
	return nil
}

func (x *UpstreamResponseModifications) GetAppendHeaders() map[string]*StringList {
	if x != nil {
		return x.AppendHeaders
	}
	return nil
}

func (x *UpstreamResponseModifications) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *UpstreamResponseModifications) GetBodyPresent() bool {
	if x != nil {
		return x.BodyPresent
	}
	return false
}

func (x *UpstreamResponseModifications) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpstreamResponseModifications) GetStatusCodePresent() bool {
	if x != nil {
		return x.StatusCodePresent
	}
	return false
}

func (x *UpstreamResponseModifications) GetAnalyticsMetadata() *structpb.Struct {
	if x != nil {
		return x.AnalyticsMetadata
	}
	return nil
}

type ImmediateResponseAction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StatusCode        int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers           map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body              []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	AnalyticsMetadata *structpb.Struct       `protobuf:"bytes,4,opt,name=analytics_metadata,json=analyticsMetadata,proto3" json:"analytics_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImmediateResponseAction) Reset() {
	*x = ImmediateResponseAction{}
	mi := &file_python_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmediateResponseAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmediateResponseAction) ProtoMessage() {}

func (x *ImmediateResponseAction) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmediateResponseAction.ProtoReflect.Descriptor instead.
func (*ImmediateResponseAction) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{15}
}

func (x *ImmediateResponseAction) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ImmediateResponseAction) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ImmediateResponseAction) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ImmediateResponseAction) GetAnalyticsMetadata() *structpb.Struct {
	if x != nil {
		return x.AnalyticsMetadata
	}
	return nil
}

type ExecutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PolicyName    string                 `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyVersion string                 `protobuf:"bytes,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	ErrorType     string                 `protobuf:"bytes,4,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // "execution_error", "timeout"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionError) Reset() {
	*x = ExecutionError{}
	mi := &file_python_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionError) ProtoMessage() {}

func (x *ExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionError.ProtoReflect.Descriptor instead.
func (*ExecutionError) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{16}
}

func (x *ExecutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionError) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *ExecutionError) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *ExecutionError) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_python_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{17}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ready          bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	LoadedPolicies int32                  `protobuf:"varint,2,opt,name=loaded_policies,json=loadedPolicies,proto3" json:"loaded_policies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_python_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthCheckResponse) GetLoadedPolicies() int32 {
	if x != nil {
		return x.LoadedPolicies
	}
	return 0
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_python_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_python_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_python_executor_proto_rawDescGZIP(), []int{19}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_python_executor_proto protoreflect.FileDescriptor

const file_python_executor_proto_rawDesc = "" +
	"\n" +
	"\x15python_executor.proto\x12\x16wso2.gateway.python.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb4\x04\n" +
	"\x10ExecutionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\tR\rpolicyVersion\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12/\n" +
	"\x06params\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06params\x12Q\n" +
	"\x0frequest_context\x18\x06 \x01(\v2&.wso2.gateway.python.v1.RequestContextH\x00R\x0erequestContext\x12T\n" +
	"\x10response_context\x18\a \x01(\v2'.wso2.gateway.python.v1.ResponseContextH\x00R\x0fresponseContext\x12L\n" +
	"\x0eshared_context\x18\b \x01(\v2%.wso2.gateway.python.v1.SharedContextR\rsharedContext\x12O\n" +
	"\x0fpolicy_metadata\x18\t \x01(\v2&.wso2.gateway.python.v1.PolicyMetadataR\x0epolicyMetadata\x12\x1f\n" +
	"\vinstance_id\x18\n" +
	" \x01(\tR\n" +
	"instanceIdB\t\n" +
	"\acontext\"\xef\x02\n" +
	"\x11ExecutionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12T\n" +
	"\x0erequest_result\x18\x02 \x01(\v2+.wso2.gateway.python.v1.RequestActionResultH\x00R\rrequestResult\x12W\n" +
	"\x0fresponse_result\x18\x03 \x01(\v2,.wso2.gateway.python.v1.ResponseActionResultH\x00R\x0eresponseResult\x12>\n" +
	"\x05error\x18\x04 \x01(\v2&.wso2.gateway.python.v1.ExecutionErrorH\x00R\x05error\x12B\n" +
	"\x10updated_metadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x0fupdatedMetadataB\b\n" +
	"\x06result\"\xcc\x01\n" +
	"\x0eProcessingMode\x12.\n" +
	"\x13request_header_mode\x18\x01 \x01(\tR\x11requestHeaderMode\x12*\n" +
	"\x11request_body_mode\x18\x02 \x01(\tR\x0frequestBodyMode\x120\n" +
	"\x14response_header_mode\x18\x03 \x01(\tR\x12responseHeaderMode\x12,\n" +
	"\x12response_body_mode\x18\x04 \x01(\tR\x10responseBodyMode\"\xdd\x01\n" +
	"\x11InitPolicyRequest\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\tR\rpolicyVersion\x12O\n" +
	"\x0fpolicy_metadata\x18\x03 \x01(\v2&.wso2.gateway.python.v1.PolicyMetadataR\x0epolicyMetadata\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xc5\x01\n" +
	"\x12InitPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12O\n" +
	"\x0fprocessing_mode\x18\x04 \x01(\v2&.wso2.gateway.python.v1.ProcessingModeR\x0eprocessingMode\"7\n" +
	"\x14DestroyPolicyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"V\n" +
	"\x15DestroyPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xd3\x03\n" +
	"\rSharedContext\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x15\n" +
	"\x06api_id\x18\x04 \x01(\tR\x05apiId\x12\x19\n" +
	"\bapi_name\x18\x05 \x01(\tR\aapiName\x12\x1f\n" +
	"\vapi_version\x18\x06 \x01(\tR\n" +
	"apiVersion\x12\x19\n" +
	"\bapi_kind\x18\a \x01(\tR\aapiKind\x12\x1f\n" +
	"\vapi_context\x18\b \x01(\tR\n" +
	"apiContext\x12%\n" +
	"\x0eoperation_path\x18\t \x01(\tR\roperationPath\x12Y\n" +
	"\fauth_context\x18\n" +
	" \x03(\v26.wso2.gateway.python.v1.SharedContext.AuthContextEntryR\vauthContext\x1a>\n" +
	"\x10AuthContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x02\n" +
	"\x0eRequestContext\x12M\n" +
	"\aheaders\x18\x01 \x03(\v23.wso2.gateway.python.v1.RequestContext.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12!\n" +
	"\fbody_present\x18\x03 \x01(\bR\vbodyPresent\x12\"\n" +
	"\rend_of_stream\x18\x04 \x01(\bR\vendOfStream\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1c\n" +
	"\tauthority\x18\a \x01(\tR\tauthority\x12\x16\n" +
	"\x06scheme\x18\b \x01(\tR\x06scheme\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x04\n" +
	"\x0fResponseContext\x12d\n" +
	"\x0frequest_headers\x18\x01 \x03(\v2;.wso2.gateway.python.v1.ResponseContext.RequestHeadersEntryR\x0erequestHeaders\x12!\n" +
	"\frequest_body\x18\x02 \x01(\fR\vrequestBody\x12!\n" +
	"\frequest_path\x18\x03 \x01(\tR\vrequestPath\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12g\n" +
	"\x10response_headers\x18\x05 \x03(\v2<.wso2.gateway.python.v1.ResponseContext.ResponseHeadersEntryR\x0fresponseHeaders\x12#\n" +
	"\rresponse_body\x18\x06 \x01(\fR\fresponseBody\x122\n" +
	"\x15response_body_present\x18\a \x01(\bR\x13responseBodyPresent\x12'\n" +
	"\x0fresponse_status\x18\b \x01(\x05R\x0eresponseStatus\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x0ePolicyMetadata\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\tR\trouteName\x12\x15\n" +
	"\x06api_id\x18\x02 \x01(\tR\x05apiId\x12\x19\n" +
	"\bapi_name\x18\x03 \x01(\tR\aapiName\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12\x1f\n" +
	"\vattached_to\x18\x05 \x01(\tR\n" +
	"attachedTo\"\xe4\x01\n" +
	"\x13RequestActionResult\x12a\n" +
	"\x10continue_request\x18\x01 \x01(\v24.wso2.gateway.python.v1.UpstreamRequestModificationsH\x00R\x0fcontinueRequest\x12`\n" +
	"\x12immediate_response\x18\x02 \x01(\v2/.wso2.gateway.python.v1.ImmediateResponseActionH\x00R\x11immediateResponseB\b\n" +
	"\x06action\"\x86\x01\n" +
	"\x14ResponseActionResult\x12d\n" +
	"\x11continue_response\x18\x01 \x01(\v25.wso2.gateway.python.v1.UpstreamResponseModificationsH\x00R\x10continueResponseB\b\n" +
	"\x06action\"\xb6\x05\n" +
	"\x1cUpstreamRequestModifications\x12e\n" +
	"\vset_headers\x18\x01 \x03(\v2D.wso2.gateway.python.v1.UpstreamRequestModifications.SetHeadersEntryR\n" +
	"setHeaders\x12%\n" +
	"\x0eremove_headers\x18\x02 \x03(\tR\rremoveHeaders\x12n\n" +
	"\x0eappend_headers\x18\x03 \x03(\v2G.wso2.gateway.python.v1.UpstreamRequestModifications.AppendHeadersEntryR\rappendHeaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12!\n" +
	"\fbody_present\x18\x05 \x01(\bR\vbodyPresent\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12!\n" +
	"\fpath_present\x18\a \x01(\bR\vpathPresent\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\x12%\n" +
	"\x0emethod_present\x18\t \x01(\bR\rmethodPresent\x12F\n" +
	"\x12analytics_metadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x11analyticsMetadata\x1a=\n" +
	"\x0fSetHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ad\n" +
	"\x12AppendHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".wso2.gateway.python.v1.StringListR\x05value:\x028\x01\"\x94\x05\n" +
	"\x1dUpstreamResponseModifications\x12f\n" +
	"\vset_headers\x18\x01 \x03(\v2E.wso2.gateway.python.v1.UpstreamResponseModifications.SetHeadersEntryR\n" +
	"setHeaders\x12%\n" +
	"\x0eremove_headers\x18\x02 \x03(\tR\rremoveHeaders\x12o\n" +
	"\x0eappend_headers\x18\x03 \x03(\v2H.wso2.gateway.python.v1.UpstreamResponseModifications.AppendHeadersEntryR\rappendHeaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12!\n" +
	"\fbody_present\x18\x05 \x01(\bR\vbodyPresent\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12.\n" +
	"\x13status_code_present\x18\a \x01(\bR\x11statusCodePresent\x12F\n" +
	"\x12analytics_metadata\x18\b \x01(\v2\x17.google.protobuf.StructR\x11analyticsMetadata\x1a=\n" +
	"\x0fSetHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ad\n" +
	"\x12AppendHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".wso2.gateway.python.v1.StringListR\x05value:\x028\x01\"\xaa\x02\n" +
	"\x17ImmediateResponseAction\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12V\n" +
	"\aheaders\x18\x02 \x03(\v2<.wso2.gateway.python.v1.ImmediateResponseAction.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12F\n" +
	"\x12analytics_metadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x11analyticsMetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x0eExecutionError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\tR\rpolicyVersion\x12\x1d\n" +
	"\n" +
	"error_type\x18\x04 \x01(\tR\terrorType\"\x14\n" +
	"\x12HealthCheckRequest\"T\n" +
	"\x13HealthCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12'\n" +
	"\x0floaded_policies\x18\x02 \x01(\x05R\x0eloadedPolicies\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\xbc\x03\n" +
	"\x15PythonExecutorService\x12h\n" +
	"\rExecuteStream\x12(.wso2.gateway.python.v1.ExecutionRequest\x1a).wso2.gateway.python.v1.ExecutionResponse(\x010\x01\x12f\n" +
	"\vHealthCheck\x12*.wso2.gateway.python.v1.HealthCheckRequest\x1a+.wso2.gateway.python.v1.HealthCheckResponse\x12c\n" +
	"\n" +
	"InitPolicy\x12).wso2.gateway.python.v1.InitPolicyRequest\x1a*.wso2.gateway.python.v1.InitPolicyResponse\x12l\n" +
	"\rDestroyPolicy\x12,.wso2.gateway.python.v1.DestroyPolicyRequest\x1a-.wso2.gateway.python.v1.DestroyPolicyResponseB`Z^github.com/wso2/api-platform/gateway/gateway-runtime/policy-engine/internal/pythonbridge/protob\x06proto3"

var (
	file_python_executor_proto_rawDescOnce sync.Once
	file_python_executor_proto_rawDescData []byte
)

func file_python_executor_proto_rawDescGZIP() []byte {
	file_python_executor_proto_rawDescOnce.Do(func() {
		file_python_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_python_executor_proto_rawDesc), len(file_python_executor_proto_rawDesc)))
	})
	return file_python_executor_proto_rawDescData
}

var file_python_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_python_executor_proto_goTypes = []any{
	(*ExecutionRequest)(nil),              // 0: wso2.gateway.python.v1.ExecutionRequest
	(*ExecutionResponse)(nil),             // 1: wso2.gateway.python.v1.ExecutionResponse
	(*ProcessingMode)(nil),                // 2: wso2.gateway.python.v1.ProcessingMode
	(*InitPolicyRequest)(nil),             // 3: wso2.gateway.python.v1.InitPolicyRequest
	(*InitPolicyResponse)(nil),            // 4: wso2.gateway.python.v1.InitPolicyResponse
	(*DestroyPolicyRequest)(nil),          // 5: wso2.gateway.python.v1.DestroyPolicyRequest
	(*DestroyPolicyResponse)(nil),         // 6: wso2.gateway.python.v1.DestroyPolicyResponse
	(*SharedContext)(nil),                 // 7: wso2.gateway.python.v1.SharedContext
	(*RequestContext)(nil),                // 8: wso2.gateway.python.v1.RequestContext
	(*ResponseContext)(nil),               // 9: wso2.gateway.python.v1.ResponseContext
	(*PolicyMetadata)(nil),                // 10: wso2.gateway.python.v1.PolicyMetadata
	(*RequestActionResult)(nil),           // 11: wso2.gateway.python.v1.RequestActionResult
	(*ResponseActionResult)(nil),          // 12: wso2.gateway.python.v1.ResponseActionResult
	(*UpstreamRequestModifications)(nil),  // 13: wso2.gateway.python.v1.UpstreamRequestModifications
	(*UpstreamResponseModifications)(nil), // 14: wso2.gateway.python.v1.UpstreamResponseModifications
	(*ImmediateResponseAction)(nil),       // 15: wso2.gateway.python.v1.ImmediateResponseAction
	(*ExecutionError)(nil),                // 16: wso2.gateway.python.v1.ExecutionError
	(*HealthCheckRequest)(nil),            // 17: wso2.gateway.python.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),           // 18: wso2.gateway.python.v1.HealthCheckResponse
	(*StringList)(nil),                    // 19: wso2.gateway.python.v1.StringList
	nil,                                   // 20: wso2.gateway.python.v1.SharedContext.AuthContextEntry
	nil,                                   // 21: wso2.gateway.python.v1.RequestContext.HeadersEntry
	nil,                                   // 22: wso2.gateway.python.v1.ResponseContext.RequestHeadersEntry
	nil,                                   // 23: wso2.gateway.python.v1.ResponseContext.ResponseHeadersEntry
	nil,                                   // 24: wso2.gateway.python.v1.UpstreamRequestModifications.SetHeadersEntry
	nil,                                   // 25: wso2.gateway.python.v1.UpstreamRequestModifications.AppendHeadersEntry
	nil,                                   // 26: wso2.gateway.python.v1.UpstreamResponseModifications.SetHeadersEntry
	nil,                                   // 27: wso2.gateway.python.v1.UpstreamResponseModifications.AppendHeadersEntry
	nil,                                   // 28: wso2.gateway.python.v1.ImmediateResponseAction.HeadersEntry
	(*structpb.Struct)(nil),               // 29: google.protobuf.Struct
}
var file_python_executor_proto_depIdxs = []int32{
	29, // 0: wso2.gateway.python.v1.ExecutionRequest.params:type_name -> google.protobuf.Struct
	8,  // 1: wso2.gateway.python.v1.ExecutionRequest.request_context:type_name -> wso2.gateway.python.v1.RequestContext
	9,  // 2: wso2.gateway.python.v1.ExecutionRequest.response_context:type_name -> wso2.gateway.python.v1.ResponseContext
	7,  // 3: wso2.gateway.python.v1.ExecutionRequest.shared_context:type_name -> wso2.gateway.python.v1.SharedContext
	10, // 4: wso2.gateway.python.v1.ExecutionRequest.policy_metadata:type_name -> wso2.gateway.python.v1.PolicyMetadata
	11, // 5: wso2.gateway.python.v1.ExecutionResponse.request_result:type_name -> wso2.gateway.python.v1.RequestActionResult
	12, // 6: wso2.gateway.python.v1.ExecutionResponse.response_result:type_name -> wso2.gateway.python.v1.ResponseActionResult
	16, // 7: wso2.gateway.python.v1.ExecutionResponse.error:type_name -> wso2.gateway.python.v1.ExecutionError
	29, // 8: wso2.gateway.python.v1.ExecutionResponse.updated_metadata:type_name -> google.protobuf.Struct
	10, // 9: wso2.gateway.python.v1.InitPolicyRequest.policy_metadata:type_name -> wso2.gateway.python.v1.PolicyMetadata
	29, // 10: wso2.gateway.python.v1.InitPolicyRequest.params:type_name -> google.protobuf.Struct
	2,  // 11: wso2.gateway.python.v1.InitPolicyResponse.processing_mode:type_name -> wso2.gateway.python.v1.ProcessingMode
	29, // 12: wso2.gateway.python.v1.SharedContext.metadata:type_name -> google.protobuf.Struct
	20, // 13: wso2.gateway.python.v1.SharedContext.auth_context:type_name -> wso2.gateway.python.v1.SharedContext.AuthContextEntry
	21, // 14: wso2.gateway.python.v1.RequestContext.headers:type_name -> wso2.gateway.python.v1.RequestContext.HeadersEntry
	22, // 15: wso2.gateway.python.v1.ResponseContext.request_headers:type_name -> wso2.gateway.python.v1.ResponseContext.RequestHeadersEntry
	23, // 16: wso2.gateway.python.v1.ResponseContext.response_headers:type_name -> wso2.gateway.python.v1.ResponseContext.ResponseHeadersEntry
	13, // 17: wso2.gateway.python.v1.RequestActionResult.continue_request:type_name -> wso2.gateway.python.v1.UpstreamRequestModifications
	15, // 18: wso2.gateway.python.v1.RequestActionResult.immediate_response:type_name -> wso2.gateway.python.v1.ImmediateResponseAction
	14, // 19: wso2.gateway.python.v1.ResponseActionResult.continue_response:type_name -> wso2.gateway.python.v1.UpstreamResponseModifications
	24, // 20: wso2.gateway.python.v1.UpstreamRequestModifications.set_headers:type_name -> wso2.gateway.python.v1.UpstreamRequestModifications.SetHeadersEntry
	25, // 21: wso2.gateway.python.v1.UpstreamRequestModifications.append_headers:type_name -> wso2.gateway.python.v1.UpstreamRequestModifications.AppendHeadersEntry
	29, // 22: wso2.gateway.python.v1.UpstreamRequestModifications.analytics_metadata:type_name -> google.protobuf.Struct
	26, // 23: wso2.gateway.python.v1.UpstreamResponseModifications.set_headers:type_name -> wso2.gateway.python.v1.UpstreamResponseModifications.SetHeadersEntry
	27, // 24: wso2.gateway.python.v1.UpstreamResponseModifications.append_headers:type_name -> wso2.gateway.python.v1.UpstreamResponseModifications.AppendHeadersEntry
	29, // 25: wso2.gateway.python.v1.UpstreamResponseModifications.analytics_metadata:type_name -> google.protobuf.Struct
	28, // 26: wso2.gateway.python.v1.ImmediateResponseAction.headers:type_name -> wso2.gateway.python.v1.ImmediateResponseAction.HeadersEntry
	29, // 27: wso2.gateway.python.v1.ImmediateResponseAction.analytics_metadata:type_name -> google.protobuf.Struct
	19, // 28: wso2.gateway.python.v1.UpstreamRequestModifications.AppendHeadersEntry.value:type_name -> wso2.gateway.python.v1.StringList
	19, // 29: wso2.gateway.python.v1.UpstreamResponseModifications.AppendHeadersEntry.value:type_name -> wso2.gateway.python.v1.StringList
	0,  // 30: wso2.gateway.python.v1.PythonExecutorService.ExecuteStream:input_type -> wso2.gateway.python.v1.ExecutionRequest
	17, // 31: wso2.gateway.python.v1.PythonExecutorService.HealthCheck:input_type -> wso2.gateway.python.v1.HealthCheckRequest
	3,  // 32: wso2.gateway.python.v1.PythonExecutorService.InitPolicy:input_type -> wso2.gateway.python.v1.InitPolicyRequest
	5,  // 33: wso2.gateway.python.v1.PythonExecutorService.DestroyPolicy:input_type -> wso2.gateway.python.v1.DestroyPolicyRequest
	1,  // 34: wso2.gateway.python.v1.PythonExecutorService.ExecuteStream:output_type -> wso2.gateway.python.v1.ExecutionResponse
	18, // 35: wso2.gateway.python.v1.PythonExecutorService.HealthCheck:output_type -> wso2.gateway.python.v1.HealthCheckResponse
	4,  // 36: wso2.gateway.python.v1.PythonExecutorService.InitPolicy:output_type -> wso2.gateway.python.v1.InitPolicyResponse
	6,  // 37: wso2.gateway.python.v1.PythonExecutorService.DestroyPolicy:output_type -> wso2.gateway.python.v1.DestroyPolicyResponse
	34, // [34:38] is the sub-list for method output_type
	30, // [30:34] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_python_executor_proto_init() }
func file_python_executor_proto_init() {
	if File_python_executor_proto != nil {
		return
	}
	file_python_executor_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecutionRequest_RequestContext)(nil),
		(*ExecutionRequest_ResponseContext)(nil),
	}
	file_python_executor_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecutionResponse_RequestResult)(nil),
		(*ExecutionResponse_ResponseResult)(nil),
		(*ExecutionResponse_Error)(nil),
	}
	file_python_executor_proto_msgTypes[11].OneofWrappers = []any{
		(*RequestActionResult_ContinueRequest)(nil),
		(*RequestActionResult_ImmediateResponse)(nil),
	}
	file_python_executor_proto_msgTypes[12].OneofWrappers = []any{
		(*ResponseActionResult_ContinueResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_python_executor_proto_rawDesc), len(file_python_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_python_executor_proto_goTypes,
		DependencyIndexes: file_python_executor_proto_depIdxs,
		MessageInfos:      file_python_executor_proto_msgTypes,
	}.Build()
	File_python_executor_proto = out.File
	file_python_executor_proto_goTypes = nil
	file_python_executor_proto_depIdxs = nil
}
