apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend-apim
  namespace: gateway-api-demo-apim
  labels:
    app: hello-backend
    app.kubernetes.io/part-of: apim-gateway-api-operator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-backend-apim
  template:
    metadata:
      labels:
        app: hello-backend-apim
    spec:
      containers:
        - name: sample-backend-apim
          image: ghcr.io/wso2/api-platform/sample-service:latest
          args:
            - "-addr"
            - ":9080"
            - "-pretty"
          ports:
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-backend-apim
  namespace: gateway-api-demo-apim
  labels:
    app.kubernetes.io/part-of: apim-gateway-api-operator-demo
spec:
  type: ClusterIP
  selector:
    app: hello-backend-apim
  ports:
    - name: http
      port: 9080
      targetPort: 9080
