#!/usr/bin/env bash
# --------------------------------------------------------------------
# Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the
# License at http://www.apache.org/licenses/LICENSE-2.0
# --------------------------------------------------------------------
#
# AI Workspace quickstart setup.
#
# Generates everything the stack requires before first start — nothing is
# auto-generated at runtime anymore:
#
#   keys.env                  APIP_CP_ENCRYPTION_KEY        at-rest encryption key
#                             APIP_CP_AUTH_JWT_SECRET_KEY   JWT signing key
#                             APIP_CP_ADMIN_USERNAME        admin login username
#                             APIP_CP_ADMIN_PASSWORD_HASH   bcrypt hash of the password
#   certs/platform-api.crt|key   TLS pair for the Platform API (SAN: localhost, platform-api)
#   certs/ai-workspace.crt|key   TLS pair for the AI Workspace  (SAN: localhost, ai-workspace)
#
# The admin password is printed once below and is NOT stored anywhere.
#
# Usage:
#   ./setup.sh                 generate anything that is missing
#   ./setup.sh --force         regenerate everything (rotates keys and credentials)
#   ./setup.sh --certs-only    generate only the TLS certificates (used by `make bff-run`)
#
#   ADMIN_USERNAME / ADMIN_PASSWORD environment variables override the generated
#   credentials (used by CI to pin known test credentials).
#
# Then start the stack:
#   docker compose --env-file keys.env up -d
# --------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE="keys.env"
CERTS_DIR="certs"
FORCE=false
CERTS_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    --certs-only) CERTS_ONLY=true ;;
    -h|--help)
      sed -n '11,35p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null 2>&1 || { echo "error: openssl is required" >&2; exit 1; }

# ---------------------------------------------------------------------------
# TLS certificates
# ---------------------------------------------------------------------------
gen_cert() {
  local name="$1" san="$2"
  if [[ "$FORCE" == false && -f "$CERTS_DIR/$name.crt" && -f "$CERTS_DIR/$name.key" ]]; then
    echo "✓ $CERTS_DIR/$name.crt already exists — keeping it"
    return
  fi
  openssl req -x509 -newkey rsa:2048 -sha256 -days 365 -nodes \
    -keyout "$CERTS_DIR/$name.key" -out "$CERTS_DIR/$name.crt" \
    -subj "/O=WSO2 API Platform/CN=$name" \
    -addext "subjectAltName=$san" >/dev/null 2>&1
  chmod 600 "$CERTS_DIR/$name.key"
  echo "✓ generated $CERTS_DIR/$name.crt / $name.key"
}

mkdir -p "$CERTS_DIR"
gen_cert "platform-api" "DNS:localhost,DNS:platform-api,DNS:host.docker.internal,IP:127.0.0.1"
gen_cert "ai-workspace" "DNS:localhost,DNS:ai-workspace,DNS:host.docker.internal,IP:127.0.0.1"

if [[ "$CERTS_ONLY" == true ]]; then
  exit 0
fi

# ---------------------------------------------------------------------------
# keys.env — secrets and admin credentials
# ---------------------------------------------------------------------------
if [[ "$FORCE" == false && -f "$ENV_FILE" ]]; then
  echo "✓ $ENV_FILE already exists — keeping it (rerun with --force to rotate keys and credentials)"
  echo
  echo "Start the stack with:"
  echo "  docker compose --env-file $ENV_FILE up -d"
  exit 0
fi

# bcrypt is not in openssl; use htpasswd when available, otherwise the httpd image.
bcrypt_hash() {
  local password="$1"
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -nbB -C 10 "" "$password" | cut -d: -f2 | tr -d '\r\n'
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm httpd:2.4-alpine htpasswd -nbB -C 10 "" "$password" | cut -d: -f2 | tr -d '\r\n'
  else
    echo "error: need either htpasswd (apache2-utils / httpd-tools) or docker to bcrypt-hash the admin password" >&2
    exit 1
  fi
}

ENCRYPTION_KEY="$(openssl rand -hex 32)"
JWT_SECRET_KEY="$(openssl rand -hex 32)"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin-$(openssl rand -hex 2)}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-16)}"
ADMIN_PASSWORD_HASH="$(bcrypt_hash "$ADMIN_PASSWORD")"

umask 177
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") — do not commit.
# The admin password is not stored here; it was printed once by setup.sh.
APIP_CP_ENCRYPTION_KEY=$ENCRYPTION_KEY
APIP_CP_AUTH_JWT_SECRET_KEY=$JWT_SECRET_KEY
APIP_CP_ADMIN_USERNAME=$ADMIN_USERNAME
APIP_CP_ADMIN_PASSWORD_HASH=$ADMIN_PASSWORD_HASH
EOF
umask 022
echo "✓ wrote $ENV_FILE"

echo
echo "============================================================"
echo "  Admin user created"
echo
echo "    username: $ADMIN_USERNAME"
echo "    password: $ADMIN_PASSWORD"
echo
echo "  Save these now — the password is shown only once and is"
echo "  stored only as a bcrypt hash in $ENV_FILE."
echo "  Rotate with: ./setup.sh --force"
echo "============================================================"
echo
echo "Start the stack with:"
echo "  docker compose --env-file $ENV_FILE up -d"
