DROP TABLE IF EXISTS "DP_EVENT_DELIVERY";
DROP TABLE IF EXISTS "DP_EVENT";
DROP TABLE IF EXISTS "DP_API_KEY";
DROP TABLE IF EXISTS "DP_API_FLOW";
DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "DP_APP_KEY_MAPPING";
DROP TABLE IF EXISTS "DP_KEY_MANAGER";
DROP TABLE IF EXISTS "DP_API_SUBSCRIPTION";
DROP TABLE IF EXISTS "DP_APPLICATION" CASCADE;
DROP TABLE IF EXISTS "DP_API_SUBSCRIPTION_POLICY";
DROP TABLE IF EXISTS "DP_SUBSCRIPTION_POLICY";
DROP TABLE IF EXISTS "DP_API_IMAGEDATA";
DROP TABLE IF EXISTS "DP_API_CONTENT";
DROP TABLE IF EXISTS "DP_API_LABELS";
DROP TABLE IF EXISTS "DP_API_METADATA" CASCADE;
DROP TABLE IF EXISTS "DP_IDENTITY_PROVIDER";
DROP TABLE IF EXISTS "DP_ORGANIZATION_ASSETS";
DROP TABLE IF EXISTS "DP_VIEW_LABELS";
DROP TABLE IF EXISTS "DP_LABELS" CASCADE;
DROP TABLE IF EXISTS "DP_VIEWS" CASCADE;
DROP TABLE IF EXISTS "DP_PROVIDER";
DROP TABLE IF EXISTS "DP_ORGANIZATION" CASCADE;

-- DP_ORGANIZATION
CREATE TABLE "DP_ORGANIZATION" (
    "ORG_ID" VARCHAR(256) NOT NULL,
    "ORG_NAME" VARCHAR(256) NOT NULL,
    "BUSINESS_OWNER" VARCHAR(256),
    "BUSINESS_OWNER_CONTACT" VARCHAR(256),
    "BUSINESS_OWNER_EMAIL" VARCHAR(256),
    "ORG_HANDLE" VARCHAR(255) NOT NULL,
    "ROLE_CLAIM_NAME" VARCHAR(255),
    "GROUPS_CLAIM_NAME" VARCHAR(255),
    "ORGANIZATION_CLAIM_NAME" VARCHAR(255),
    "ORGANIZATION_IDENTIFIER" VARCHAR(255) NOT NULL,
    "ADMIN_ROLE" VARCHAR(255),
    "SUBSCRIBER_ROLE" VARCHAR(255),
    "SUPER_ADMIN_ROLE" VARCHAR(255),
    "ORG_CONFIG" JSON NOT NULL,
    PRIMARY KEY("ORG_ID"),
    UNIQUE ("ORG_NAME"),
    UNIQUE ("ORG_HANDLE"),
    UNIQUE ("ORGANIZATION_IDENTIFIER")
);

-- DP_PROVIDER
CREATE TABLE "DP_PROVIDER" (
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "PROPERTY" VARCHAR(256) NOT NULL,
    "VALUE" VARCHAR(256) NOT NULL,
    PRIMARY KEY("ORG_ID", "NAME", "PROPERTY"),
    UNIQUE ("NAME", "PROPERTY", "ORG_ID"),
    FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_VIEWS
CREATE TABLE "DP_VIEWS" (
    "VIEW_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "DISPLAY_NAME" VARCHAR(256) NOT NULL,
    PRIMARY KEY("VIEW_ID"),
    UNIQUE ("NAME", "DISPLAY_NAME", "ORG_ID"),
    FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_LABELS
CREATE TABLE "DP_LABELS" (
    "LABEL_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "DISPLAY_NAME" VARCHAR(256) NOT NULL,
    PRIMARY KEY("LABEL_ID"),
    UNIQUE ("NAME", "DISPLAY_NAME", "ORG_ID"),
    FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_VIEW_LABELS
CREATE TABLE "DP_VIEW_LABELS" (
    "ID" VARCHAR(256) NOT NULL,
    "LABEL_ID" VARCHAR(256) NOT NULL,
    "VIEW_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    PRIMARY KEY("ID"),
    UNIQUE ("LABEL_ID", "VIEW_ID", "ORG_ID"),
    FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY("LABEL_ID") REFERENCES "DP_LABELS"("LABEL_ID") ON DELETE CASCADE,
    FOREIGN KEY("VIEW_ID") REFERENCES "DP_VIEWS"("VIEW_ID") ON DELETE CASCADE
);

-- DP_ORGANIZATION_ASSETS
CREATE TABLE "DP_ORGANIZATION_ASSETS" (
	"ASSET_ID" VARCHAR(256) NOT NULL,
	"FILE_NAME" VARCHAR(256) NOT NULL,
	"FILE_CONTENT" BYTEA NOT NULL,
	"FILE_TYPE" VARCHAR(256) NOT NULL,
	"FILE_PATH" VARCHAR(1000) NOT NULL,
	"ORG_ID" VARCHAR(256) NOT NULL,
    "VIEW_ID" VARCHAR(256),
	PRIMARY KEY("ASSET_ID"),
	UNIQUE ("FILE_NAME", "FILE_TYPE", "FILE_PATH", "ORG_ID", "VIEW_ID"),
	FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY("VIEW_ID") REFERENCES "DP_VIEWS"("VIEW_ID") ON DELETE CASCADE
);

-- DP_IDENTITY_PROVIDER
CREATE TABLE IF NOT EXISTS "DP_IDENTITY_PROVIDER" (
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "ISSUER" VARCHAR(256) NOT NULL,
    "AUTHORIZATION_URL" VARCHAR(256) NOT NULL,
    "TOKEN_URL" VARCHAR(256) NOT NULL,
    "USER_INFOR_URL" VARCHAR(256),
    "CLIENT_ID" VARCHAR(256) NOT NULL,
    "CALLBACK_URL" VARCHAR(256) NOT NULL,
    "SCOPE" VARCHAR(256) NOT NULL,
    "SIGNUP_URL" VARCHAR(256),
    "LOGOUT_URL" VARCHAR(256) NOT NULL,
    "LOGOUT_REDIRECT_URL" VARCHAR(256) NOT NULL,
    "JWKS_URL" VARCHAR(256),
    "CERTIFICATE" VARCHAR(5000),
    PRIMARY KEY ("ORG_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_API_METADATA
CREATE TABLE "DP_API_METADATA" (
    "API_ID" VARCHAR(256) NOT NULL,
    "REFERENCE_ID" VARCHAR(256),
    "ORG_ID" VARCHAR(256) NOT NULL,
    "API_NAME" VARCHAR(256) NOT NULL,
    "STATUS" VARCHAR(256) NOT NULL,
    "API_HANDLE" VARCHAR(256) NOT NULL,
    "API_DESCRIPTION" VARCHAR(4096) NOT NULL,
    "API_VERSION" VARCHAR(256) NOT NULL,
    "API_TYPE" VARCHAR(256) NOT NULL,
    "VISIBILITY" VARCHAR(256) NOT NULL,
    "VISIBLE_GROUPS" VARCHAR(256),
    "TECHNICAL_OWNER" VARCHAR(256),
    "BUSINESS_OWNER" VARCHAR(256),
    "TECHNICAL_OWNER_EMAIL" VARCHAR(256),
    "BUSINESS_OWNER_EMAIL" VARCHAR(256),
    "PRODUCTION_URL" VARCHAR(256),
    "SANDBOX_URL" VARCHAR(256),
    "METADATA_SEARCH" JSON,
    "PROVIDER" VARCHAR(256),
    "TAGS" VARCHAR(256),
    "GATEWAY_TYPE" VARCHAR(256),
    "AGENT_VISIBILITY" VARCHAR(32) NOT NULL DEFAULT 'VISIBLE' CHECK ("AGENT_VISIBILITY" IN ('VISIBLE', 'HIDDEN')),
    PRIMARY KEY ("API_ID"),
    UNIQUE ("ORG_ID", "API_NAME", "API_VERSION"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_METADATA_API_ID" ON "DP_API_METADATA"("API_ID");
CREATE INDEX IF NOT EXISTS "IDX_METADATA_ORG_ID" ON "DP_API_METADATA"("ORG_ID");
CREATE INDEX IF NOT EXISTS "IDX_METADATA_SEARCH" ON "DP_API_METADATA" 
    USING gin(to_tsvector('english', "METADATA_SEARCH"));

-- DP_API_LABELS
CREATE TABLE "DP_API_LABELS" (
    "ID" VARCHAR(256) NOT NULL,
    "LABEL_ID" VARCHAR(256) NOT NULL,
    "API_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    PRIMARY KEY("ID"),
    UNIQUE ("LABEL_ID", "API_ID", "ORG_ID"),
    FOREIGN KEY("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY("LABEL_ID") REFERENCES "DP_LABELS"("LABEL_ID") ON DELETE CASCADE,
    FOREIGN KEY("API_ID") REFERENCES "DP_API_METADATA"("API_ID") ON DELETE CASCADE
);

-- DP_API_CONTENT
CREATE TABLE "DP_API_CONTENT" (
    "API_FILE" BYTEA,
    "FILE_NAME" VARCHAR(256) NOT NULL,
    "TYPE" VARCHAR(256) NOT NULL,
    "API_ID" VARCHAR(256) NOT NULL,
    PRIMARY KEY ("API_ID", "FILE_NAME", "TYPE"),
    FOREIGN KEY ("API_ID") REFERENCES "DP_API_METADATA"("API_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_CONTENT_API_ID" ON "DP_API_CONTENT"("API_ID");
CREATE INDEX IF NOT EXISTS "IDX_CONTENT_FILE_NAME" ON "DP_API_CONTENT"("FILE_NAME");

-- DP_API_IMAGEDATA
CREATE TABLE "DP_API_IMAGEDATA" (
    "IMAGE_NAME" VARCHAR(256) NOT NULL,
    "IMAGE_TAG" VARCHAR(256) NOT NULL,
    "API_ID" VARCHAR(256) NOT NULL,
    PRIMARY KEY ("API_ID", "IMAGE_NAME", "IMAGE_TAG"),
    FOREIGN KEY ("API_ID") REFERENCES "DP_API_METADATA"("API_ID") ON DELETE CASCADE
);

-- DP_SUBSCRIPTION_POLICY
CREATE TABLE "DP_SUBSCRIPTION_POLICY" (
    "ORG_ID" VARCHAR(256) NOT NULL,
    "POLICY_ID" VARCHAR(256) NOT NULL,
    "POLICY_NAME" VARCHAR(256) NOT NULL,
    "DISPLAY_NAME" VARCHAR(256) NOT NULL,
    "DESCRIPTION" VARCHAR(256),
    "REQUEST_COUNT" VARCHAR(256),
    "REF_ID" VARCHAR(256),
    PRIMARY KEY ("POLICY_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_API_SUBSCRIPTION_POLICY
CREATE TABLE "DP_API_SUBSCRIPTION_POLICY" (
    "POLICY_ID" VARCHAR(256) NOT NULL,
    "API_ID" VARCHAR(256) NOT NULL,
    PRIMARY KEY ("API_ID", "POLICY_ID"),
    FOREIGN KEY ("API_ID") REFERENCES "DP_API_METADATA"("API_ID") ON DELETE CASCADE,
    FOREIGN KEY ("POLICY_ID") REFERENCES "DP_SUBSCRIPTION_POLICY"("POLICY_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_SUBSCRIPTION_POLICY_API_ID" ON "DP_API_SUBSCRIPTION_POLICY"("API_ID");

-- DP_APPLICATION
CREATE TABLE "DP_APPLICATION" (
    "APP_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "CREATED_BY" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "DESCRIPTION" VARCHAR(256),
    "TYPE" VARCHAR(256) NOT NULL,
    PRIMARY KEY ("APP_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

-- DP_API_SUBSCRIPTION
CREATE TABLE "DP_API_SUBSCRIPTION" (
    "SUB_ID" VARCHAR(256) NOT NULL,
    "APP_ID" VARCHAR(256),
    "ORG_ID" VARCHAR(256) NOT NULL,
    "API_ID" VARCHAR(256) NOT NULL,
    "POLICY_ID" VARCHAR(256),
    "SUB_TOKEN"    VARCHAR(512),
    "STATUS"       VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY ("SUB_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY ("APP_ID") REFERENCES "DP_APPLICATION"("APP_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_DP_SUB_ORG_APP_API" ON "DP_API_SUBSCRIPTION" ("ORG_ID", "APP_ID", "API_ID");

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_DP_SUB_APP_BASED"
    ON "DP_API_SUBSCRIPTION" ("APP_ID", "ORG_ID", "API_ID", "POLICY_ID")
    WHERE "APP_ID" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_DP_SUB_PLATFORM"
    ON "DP_API_SUBSCRIPTION" ("ORG_ID", "API_ID", COALESCE("POLICY_ID", ''))
    WHERE "APP_ID" IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_DP_SUB_TOKEN"
    ON "DP_API_SUBSCRIPTION" ("SUB_TOKEN")
    WHERE "SUB_TOKEN" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IDX_DP_SUB_PLATFORM_ORG_API"
    ON "DP_API_SUBSCRIPTION" ("ORG_ID", "API_ID")
    WHERE "APP_ID" IS NULL;

-- DP_KEY_MANAGER: Stores OAuth2 Authorization Server configurations for each organization. --- IGNORE ---
CREATE TABLE IF NOT EXISTS "DP_KEY_MANAGER" (
    "KM_ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "TYPE" VARCHAR(32) NOT NULL CHECK ("TYPE" IN ('ASGARDEO', 'WSO2IS', 'KEYCLOAK', 'GENERIC_OIDC')),
    "ENABLED" BOOLEAN NOT NULL DEFAULT TRUE,
    "TOKEN_ENDPOINT" VARCHAR(512) NOT NULL,
    "CLIENT_REG_ENDPOINT" VARCHAR(512) NOT NULL,
    "ISSUER" VARCHAR(512),
    "JWKS_URL" VARCHAR(512),
    "ADMIN_CLIENT_ID_ENC" TEXT NOT NULL,
    "ADMIN_CLIENT_SECRET_ENC" TEXT NOT NULL,
    "SUPPORTED_GRANT_TYPES" JSON DEFAULT '["client_credentials"]',
    "SUPPORTED_SCOPES" JSON DEFAULT '["openid"]',
    "ADDITIONAL_PROPERTIES" JSON DEFAULT '{}',
    PRIMARY KEY ("KM_ID"),
    UNIQUE ("ORG_ID", "NAME"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_DP_KEY_MANAGER_ORG_ID" ON "DP_KEY_MANAGER"("ORG_ID");

-- DP_APP_KEY_MAPPING: Maps DP_APPLICATIONs to DP_KEY_MANAGER configurations, allowing each application to specify which
-- key manager (OAuth2 AS) it uses for token validation.
CREATE TABLE "DP_APP_KEY_MAPPING" (
    "MAPPING_ID" VARCHAR(256) NOT NULL,
    "APP_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "KM_ID" UUID,
    "AS_CLIENT_ID" VARCHAR(256),
    "KEY_TYPE" VARCHAR(32) NOT NULL DEFAULT 'PRODUCTION' CHECK ("KEY_TYPE" IN ('PRODUCTION', 'SANDBOX')),
    "ADDITIONAL_PROPERTIES" TEXT,
    PRIMARY KEY ("MAPPING_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY ("APP_ID") REFERENCES "DP_APPLICATION"("APP_ID") ON DELETE CASCADE,
    FOREIGN KEY ("KM_ID") REFERENCES "DP_KEY_MANAGER"("KM_ID") ON DELETE SET NULL
);

-- session: Session table for storing user sessions, used by the portal's authentication system.
CREATE TABLE "session" (
    "sid" VARCHAR NOT NULL COLLATE "default",
    "sess" JSON NOT NULL,
    "expire" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("sid")
);

CREATE INDEX IF NOT EXISTS "IDX_SESSION_EXPIRE" ON "session" ("expire");

-- DP_API_FLOW: Stores APIFlow definitions with agent prompts.
CREATE TABLE "DP_API_FLOW" (
    "API_FLOW_ID" VARCHAR(256) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "VIEW_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(256) NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "HANDLE" VARCHAR(256) NOT NULL,
    "AGENT_PROMPT" TEXT NOT NULL,
    "STATUS" VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED' CHECK ("STATUS" IN ('DRAFT', 'PUBLISHED')),
    "VISIBILITY" VARCHAR(32) NOT NULL DEFAULT 'PUBLIC' CHECK ("VISIBILITY" IN ('PUBLIC', 'PRIVATE')),
    "AGENT_VISIBILITY" VARCHAR(32) NOT NULL DEFAULT 'VISIBLE' CHECK ("AGENT_VISIBILITY" IN ('VISIBLE', 'HIDDEN')),
    "FILE_CONTENT" BYTEA,
    "CONTENT_TYPE" VARCHAR(32) CHECK ("CONTENT_TYPE" IN ('ARAZZO', 'MD')),
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("API_FLOW_ID"),
    UNIQUE ("ORG_ID", "VIEW_ID", "HANDLE"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY ("VIEW_ID") REFERENCES "DP_VIEWS"("VIEW_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_DP_API_FLOW_ORG_ID" ON "DP_API_FLOW"("ORG_ID");
CREATE INDEX IF NOT EXISTS "IDX_DP_API_FLOW_VIEW_ID" ON "DP_API_FLOW"("VIEW_ID");

-- DP_API_KEY: Stores API keys generated for APIs.
CREATE TABLE IF NOT EXISTS "DP_API_KEY" (
    "KEY_ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "API_ID" VARCHAR(256) NOT NULL,
    "SUBSCRIPTION_ID" VARCHAR(256),
    "ORG_ID" VARCHAR(256) NOT NULL,
    "NAME" VARCHAR(128) NOT NULL,
    "STATUS" VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    "EXPIRES_AT" TIMESTAMP,
    "CREATED_BY" VARCHAR(256) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),
    "REVOKED_AT" TIMESTAMP,
    PRIMARY KEY ("KEY_ID"),
    FOREIGN KEY ("ORG_ID") REFERENCES "DP_ORGANIZATION"("ORG_ID") ON DELETE CASCADE,
    FOREIGN KEY ("API_ID") REFERENCES "DP_API_METADATA"("API_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_DP_API_KEY_ORG_API" ON "DP_API_KEY" ("ORG_ID", "API_ID");

-- DP_EVENT: Stores webhook events generated by the system.
CREATE TABLE IF NOT EXISTS "DP_EVENT" (
    "EVENT_ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "EVENT_TYPE" VARCHAR(128) NOT NULL,
    "ORG_ID" VARCHAR(256) NOT NULL,
    "GATEWAY_TYPE" VARCHAR(128),
    "AGGREGATE_TYPE" VARCHAR(64) NOT NULL,
    "AGGREGATE_ID" UUID NOT NULL,
    "PAYLOAD" JSONB NOT NULL DEFAULT '{}',
    "OCCURRED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),
    "STATUS" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "IDX_DP_EVENT_STATUS_OCCURRED" ON "DP_EVENT" ("STATUS", "OCCURRED_AT");

-- DP_EVENT_DELIVERY: Stores delivery attempts for webhook events.
CREATE TABLE IF NOT EXISTS "DP_EVENT_DELIVERY" (
    "DELIVERY_ID" UUID NOT NULL DEFAULT gen_random_uuid(),
    "EVENT_ID" UUID NOT NULL,
    "SUBSCRIBER_ID" VARCHAR(128) NOT NULL,
    "TARGET_URL" TEXT NOT NULL,
    "ENCRYPTED_FIELDS" JSONB,
    "STATUS" VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    "ATTEMPT_COUNT" INTEGER NOT NULL DEFAULT 0,
    "NEXT_ATTEMPT_AT" TIMESTAMP NOT NULL DEFAULT NOW(),
    "LAST_HTTP_STATUS" INTEGER,
    "LAST_ERROR" TEXT,
    "LAST_ATTEMPT_AT" TIMESTAMP,
    "DELIVERED_AT" TIMESTAMP,
    PRIMARY KEY ("DELIVERY_ID"),
    FOREIGN KEY ("EVENT_ID") REFERENCES "DP_EVENT"("EVENT_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_DP_DELIVERY_STATUS_NEXT" ON "DP_EVENT_DELIVERY" ("STATUS", "NEXT_ATTEMPT_AT");
CREATE INDEX IF NOT EXISTS "IDX_DP_DELIVERY_EVENT_ID" ON "DP_EVENT_DELIVERY" ("EVENT_ID");
