/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package webhook

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hkdf"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/sha3"
	"encoding/base64"
	"encoding/hex"
	"strconv"
	"testing"
	"time"
)

// encryptFieldForTest mirrors the producer side (Developer Portal
// src/services/webhooks/envelopeCrypto.js, encryptField): AES-256-GCM under the HKDF-derived
// field key, with the nonce and tag carried separately from the ciphertext.
func encryptFieldForTest(t *testing.T, secret, plaintext string) *EncryptedKey {
	t.Helper()
	key, err := hkdf.Key(sha3.New256, []byte(secret), nil, fieldKeyInfo, fieldKeyBytes)
	if err != nil {
		t.Fatalf("hkdf: %v", err)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		t.Fatalf("aes: %v", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		t.Fatalf("gcm: %v", err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		t.Fatalf("nonce: %v", err)
	}
	sealed := gcm.Seal(nil, nonce, []byte(plaintext), nil)
	return &EncryptedKey{
		IV:         base64.StdEncoding.EncodeToString(nonce),
		Tag:        base64.StdEncoding.EncodeToString(sealed[len(sealed)-16:]),
		Ciphertext: base64.StdEncoding.EncodeToString(sealed[:len(sealed)-16]),
	}
}

// TestDeriveFieldKey_MatchesProducer is a known-answer test pinning this side's HKDF derivation
// to the Developer Portal's. The expected key was produced by the Node producer:
//
//	require('./src/services/webhooks/envelopeCrypto').deriveFieldKey('shared-secret').toString('hex')
//
// If this fails, the two sides no longer derive the same key and every field decryption breaks —
// check that fieldKeyInfo, the salt (empty), the hash (SHA3-256) and the length still agree.
func TestDeriveFieldKey_MatchesProducer(t *testing.T) {
	const wantHex = "aa951771c97c94be7e0eae71316c23c8bfa6da5ea49b28223cea84355bfa2e5d"

	d, err := NewDecryptor("shared-secret")
	if err != nil {
		t.Fatalf("NewDecryptor: %v", err)
	}
	if got := hex.EncodeToString(d.key); got != wantHex {
		t.Fatalf("derived key mismatch:\n got %s\nwant %s", got, wantHex)
	}
}

// TestDecryptor_DecryptsProducerEnvelope decrypts a fixture generated by the Node producer, so
// the whole wire scheme (HKDF label, base64 encoding, separate iv/tag) is pinned across languages
// and not just self-consistently within Go.
func TestDecryptor_DecryptsProducerEnvelope(t *testing.T) {
	d, err := NewDecryptor("shared-secret")
	if err != nil {
		t.Fatalf("NewDecryptor: %v", err)
	}
	enc := &EncryptedKey{
		IV:         "MD4uUhNKOl1jt0Wg",
		Tag:        "oEc3xMXQ4yZejpjFwK1UxA==",
		Ciphertext: "BRhFPvVB71qaOXJFNV+bgEgBMvpt/99sC3XF",
	}

	got, err := d.Decrypt(enc)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if want := "ap-key-9f8b7c6d5e4f3a2b1c0d"; got != want {
		t.Fatalf("plaintext mismatch: got %q want %q", got, want)
	}
}

func TestDecryptor_RoundTrip(t *testing.T) {
	const sharedSecret = "wh-shared-secret-value"
	d, err := NewDecryptor(sharedSecret)
	if err != nil {
		t.Fatalf("NewDecryptor: %v", err)
	}

	const secret = "ap-key-9f8b7c6d5e4f3a2b1c0d"
	got, err := d.Decrypt(encryptFieldForTest(t, sharedSecret, secret))
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if got != secret {
		t.Fatalf("plaintext mismatch: got %q want %q", got, secret)
	}
}

func TestDecryptor_TamperedTagFails(t *testing.T) {
	const sharedSecret = "wh-shared-secret-value"
	d, err := NewDecryptor(sharedSecret)
	if err != nil {
		t.Fatalf("NewDecryptor: %v", err)
	}
	enc := encryptFieldForTest(t, sharedSecret, "secret-value")
	enc.Tag = base64.StdEncoding.EncodeToString(make([]byte, 16)) // zeroed tag
	if _, err := d.Decrypt(enc); err == nil {
		t.Fatal("expected decryption to fail with a tampered tag")
	}
}

// TestDecryptor_WrongSecretFails covers the misconfiguration this design makes possible: the
// receiver's secret no longer matching the producer's must fail closed, not yield garbage.
func TestDecryptor_WrongSecretFails(t *testing.T) {
	enc := encryptFieldForTest(t, "the-producers-secret", "secret-value")

	d, err := NewDecryptor("a-different-secret")
	if err != nil {
		t.Fatalf("NewDecryptor: %v", err)
	}
	if _, err := d.Decrypt(enc); err == nil {
		t.Fatal("expected decryption to fail when the secret does not match the producer's")
	}
}

func TestDecryptor_NilWhenNoSecret(t *testing.T) {
	d, err := NewDecryptor("")
	if err != nil {
		t.Fatalf("NewDecryptor(\"\"): %v", err)
	}
	if d != nil {
		t.Fatalf("expected a nil Decryptor when no secret is configured, got %+v", d)
	}
	enc := &EncryptedKey{IV: "aXY=", Tag: "dGFn", Ciphertext: "Y3Q="}
	if _, err := d.Decrypt(enc); err != ErrDecryptorUnavailable {
		t.Fatalf("expected ErrDecryptorUnavailable, got %v", err)
	}
}

// sign reproduces the producer's HMAC scheme for tests.
func sign(secret string, ts int64, body []byte) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(strconv.FormatInt(ts, 10) + "." + string(body)))
	return "t=" + strconv.FormatInt(ts, 10) + ",v1=" + hex.EncodeToString(mac.Sum(nil))
}

func TestLooksLikeUniqueViolation(t *testing.T) {
	cases := []struct {
		err  error
		want bool
	}{
		{nil, false},
		{errorString("UNIQUE constraint failed: api_keys.artifact_uuid, api_keys.name"), true},
		{errorString("ERROR: duplicate key value violates unique constraint \"api_keys_pkey\""), true},
		{errorString("Violation of UNIQUE KEY constraint 'UQ_api_keys'."), true},
		{errorString("connection refused"), false},
	}
	for _, c := range cases {
		if got := looksLikeUniqueViolation(c.err); got != c.want {
			t.Errorf("looksLikeUniqueViolation(%v) = %v, want %v", c.err, got, c.want)
		}
	}
}

type errorString string

func (e errorString) Error() string { return string(e) }

func TestVerifier_Verify(t *testing.T) {
	const secret = "shared-secret"
	v := NewVerifier(secret, 5*time.Minute)
	now := time.Unix(1_700_000_000, 0)
	body := []byte(`{"event_id":"e1"}`)

	t.Run("valid", func(t *testing.T) {
		if err := v.Verify(sign(secret, now.Unix(), body), body, now); err != nil {
			t.Fatalf("expected valid signature, got %v", err)
		}
	})
	t.Run("missing header", func(t *testing.T) {
		if err := v.Verify("", body, now); err != ErrSignatureMissing {
			t.Fatalf("want ErrSignatureMissing, got %v", err)
		}
	})
	t.Run("tampered body", func(t *testing.T) {
		if err := v.Verify(sign(secret, now.Unix(), body), []byte(`{"event_id":"e2"}`), now); err != ErrSignatureInvalid {
			t.Fatalf("want ErrSignatureInvalid, got %v", err)
		}
	})
	t.Run("stale timestamp", func(t *testing.T) {
		old := now.Add(-10 * time.Minute)
		if err := v.Verify(sign(secret, old.Unix(), body), body, now); err != ErrTimestampOutOfTolerance {
			t.Fatalf("want ErrTimestampOutOfTolerance, got %v", err)
		}
	})
}
