//go:build go1.22

// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package admin

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ConfigDumpAPIMetadataStatus.
const (
	Deployed   ConfigDumpAPIMetadataStatus = "deployed"
	Failed     ConfigDumpAPIMetadataStatus = "failed"
	Pending    ConfigDumpAPIMetadataStatus = "pending"
	Undeployed ConfigDumpAPIMetadataStatus = "undeployed"
)

// CertificateResponse defines model for CertificateResponse.
type CertificateResponse struct {
	Count    *int       `json:"count,omitempty" yaml:"count,omitempty"`
	Id       *string    `json:"id,omitempty" yaml:"id,omitempty"`
	Issuer   *string    `json:"issuer,omitempty" yaml:"issuer,omitempty"`
	Name     *string    `json:"name,omitempty" yaml:"name,omitempty"`
	NotAfter *time.Time `json:"notAfter,omitempty" yaml:"notAfter,omitempty"`
	Status   *string    `json:"status,omitempty" yaml:"status,omitempty"`
	Subject  *string    `json:"subject,omitempty" yaml:"subject,omitempty"`
}

// ConfigDumpAPIItem API item in config dump response
type ConfigDumpAPIItem struct {
	Configuration *map[string]interface{} `json:"configuration,omitempty" yaml:"configuration,omitempty"`
	Id            *openapi_types.UUID     `json:"id,omitempty" yaml:"id,omitempty"`

	// Metadata Metadata for API in config dump
	Metadata *ConfigDumpAPIMetadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

// ConfigDumpAPIMetadata Metadata for API in config dump
type ConfigDumpAPIMetadata struct {
	CreatedAt  *time.Time                   `json:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	DeployedAt *time.Time                   `json:"deployedAt,omitempty" yaml:"deployedAt,omitempty"`
	Status     *ConfigDumpAPIMetadataStatus `json:"status,omitempty" yaml:"status,omitempty"`
	UpdatedAt  *time.Time                   `json:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
}

// ConfigDumpAPIMetadataStatus defines model for ConfigDumpAPIMetadata.Status.
type ConfigDumpAPIMetadataStatus string

// ConfigDumpResponse defines model for ConfigDumpResponse.
type ConfigDumpResponse struct {
	Apis         *[]ConfigDumpAPIItem      `json:"apis,omitempty" yaml:"apis,omitempty"`
	Certificates *[]CertificateResponse    `json:"certificates,omitempty" yaml:"certificates,omitempty"`
	Policies     *[]map[string]interface{} `json:"policies,omitempty" yaml:"policies,omitempty"`
	Statistics   *struct {
		TotalApis             *int `json:"totalApis,omitempty" yaml:"totalApis,omitempty"`
		TotalCertificateBytes *int `json:"totalCertificateBytes,omitempty" yaml:"totalCertificateBytes,omitempty"`
		TotalCertificates     *int `json:"totalCertificates,omitempty" yaml:"totalCertificates,omitempty"`
		TotalPolicies         *int `json:"totalPolicies,omitempty" yaml:"totalPolicies,omitempty"`
	} `json:"statistics,omitempty" yaml:"statistics,omitempty"`
	Status    *string    `json:"status,omitempty" yaml:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`

	// XdsSync xDS sync metadata included in config dump
	XdsSync *ConfigDumpXDSSync `json:"xds_sync,omitempty" yaml:"xds_sync,omitempty"`
}

// ConfigDumpXDSSync xDS sync metadata included in config dump
type ConfigDumpXDSSync struct {
	// PolicyChainVersion Latest policy chain version published by the controller
	PolicyChainVersion *string `json:"policy_chain_version,omitempty" yaml:"policy_chain_version,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message" yaml:"message"`
	Status  string `json:"status" yaml:"status"`
}

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse struct {
	// Code Error code, e.g. "forbidden".
	Code    string `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Health status ("healthy")
	Status *string `json:"status,omitempty" yaml:"status,omitempty"`

	// Timestamp Timestamp of the health check
	Timestamp *time.Time `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
}

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse struct {
	// Code Error code, e.g. "authentication_failed".
	Code    string `json:"code" yaml:"code"`
	Message string `json:"message" yaml:"message"`
}

// XDSSyncStatusResponse defines model for XDSSyncStatusResponse.
type XDSSyncStatusResponse struct {
	Component *string `json:"component,omitempty" yaml:"component,omitempty"`

	// PolicyChainVersion Latest policy chain version published by the controller
	PolicyChainVersion *string    `json:"policy_chain_version,omitempty" yaml:"policy_chain_version,omitempty"`
	Timestamp          *time.Time `json:"timestamp,omitempty" yaml:"timestamp,omitempty"`
}

// HandleAdminMcpJSONBody defines parameters for HandleAdminMcp.
type HandleAdminMcpJSONBody = map[string]interface{}

// HandleAdminMcpJSONRequestBody defines body for HandleAdminMcp for application/json ContentType.
type HandleAdminMcpJSONRequestBody = HandleAdminMcpJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Dump current configuration state
	// (GET /config_dump)
	GetConfigDump(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Administrative Model Context Protocol endpoint
	// (POST /mcp)
	HandleAdminMcp(w http.ResponseWriter, r *http.Request)
	// Get xDS policy sync status
	// (GET /xds_sync_status)
	GetXDSSyncStatus(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfigDump operation middleware
func (siw *ServerInterfaceWrapper) GetConfigDump(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfigDump(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleAdminMcp operation middleware
func (siw *ServerInterfaceWrapper) HandleAdminMcp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleAdminMcp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetXDSSyncStatus operation middleware
func (siw *ServerInterfaceWrapper) GetXDSSyncStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetXDSSyncStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/config_dump", wrapper.GetConfigDump)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("POST "+options.BaseURL+"/mcp", wrapper.HandleAdminMcp)
	m.HandleFunc("GET "+options.BaseURL+"/xds_sync_status", wrapper.GetXDSSyncStatus)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW8bu9H9KwM+D9AEkCXFuS+N+slxmsRp3QiRCxeIDItajrS84ZJ7Sa5j3UD/vRhy",
	"X6W1bKe5aYH2U+Tl7Cx5ZubMGSJfWGKy3GjU3rHJF+aSFDMefp6i9XIlE+7xA7rcaIf0OLcmpxUMRokp",
	"tKcffpMjmzCpPa7Rsu2ASdF67ryVeh0eO1eg7V3SPMP+BeNPVj6+tTI2455NmOAej7zMkA3233Ce+8L1",
	"OnPF8hdMfM/atnZkosl2wE6NXsn1qyLLT6ZnZx4zek+gS6zMvTSaTdjJ9AykxwykhiSYgyiyHGyF2mAP",
	"NDIqLI8OvjAuhKTfXE1bht4W2LOjiGsNQ1FI0YdAhp4L7jkZ/7/FFZuw/xs1wR6VkR51DnhevXQ/Fuct",
	"/108qhVYGQsBnA4u+3BY5B7FiX94eAXmymwe906TEqiLjE0+shy1oMXGHxuwFZcq/Ch0/fSqx12Ri8ft",
	"+jCid5cYz2X4l1LMPSqaIV2bz3Jr+Yb+TprKfoTnHjro8Z0bJRO54/dR+b3rkeImnZeJ28fGG8/VSQnQ",
	"PgWF5dbGX27KE99veshs2jrjrklflA+QEaWK8zzLH57Ht8Jdu41OHp4K/3g1m9EL96RgZbZX0LevZkBf",
	"hIpTQOpEFQLFfaUdsmFznaRc6usbtK4kvK7/vxLeHqIxBGMojSEvlkq6FAUsN+BTpM95a5RC+7AS+7O1",
	"xt5dXRk6x9f9befOuG0HzOKvhbQoiEdKu0Ht7KpnH6+NXUohULf3grc8yxXGpiDohVVl1nLXfrrdbyYC",
	"9yENpwZaGwAO10OYNz7mbNjfMO5CYue44YuHD/sWufLp3ag3yHa3Hd+DuAxP5iwNDzZz9rRvy53q6Xq6",
	"qJbArELeRE+QpJh8Ipr/Ssb+u+aFT42Vv6E4HEmyQ+2JTaTR13VfaaLatYDS4usj3PvF7xDtkjhmIWqH",
	"tGLJUb3F9p2p4iuodz8diCMwKaz0mxmxbjznkjuZnBQ+7cnvi4spvKR12Al+4aRex11bFLTAlYNKKaIA",
	"kiN2rhfNoYbkYhi+thjCRYptn/SGQwtZ4Txw5QykRgn6wFwvuMikXoA1CodwkudKogNvAG/QbiCsAmqR",
	"G6k94G2CuW/XUG7NEodzoqjQbAiSsI0Gs9T7nEBeIrdoKzDiX68rrN9dXgTt1UboPdnC8XAM0Ri8+YQa",
	"briSQW8BX3OpnYc9IKTIKxjoAHPt0N6gBZdyS8dLETKu+Roz1J506R/cbhAyKYTCz9ziAJwBDu8uL0C6",
	"ueYJYYACjO4F6U8gPUgHNMEIwNucBIJXG0jRIiwx4YXDCP756bTBVjrgGuKZc2s8JvQRi84UNkHgWoD0",
	"jvJcKdRrdMCdKzIE6XfxD2jtBoAyVOqVKacOz+PcEwctdjl7fxwE+lRxTxUAF8izqK87Aw6ddSRwWayD",
	"Oen6N9zjZ76B0yYKcz3XFyk6rM/ngFuEEIcAHcVAoCjzM0JYRik31sMTgSteKD+BF+MXx0+DxxOlWv7u",
	"SEYoGQvuKbC5pjcdz+4sMzrbfqrAkzvq7ulgrilK/lD11eqXEqKsQugW4Uvj05gfJZuhgMWI53IUzEY3",
	"z0bxvAvIuU/rzFC45skGFvUqV5IH2OeaNKmuP6xw5aHQnU2GFPLSU99i+xGFEHg6PxuwmpLZs+F4OKYs",
	"MTlqnks2Yc+H4+FzUn/cp4EDRxHS66AKJ1/YGv0+G35AbyXeYEnW1D89QlJYS7CTCMCqe/dsLmpQqdeT",
	"uT4CSpNqXgsR6wzZrjJRhpNsLfuHwJXUsmNgcS2dR0qF9phEy7ONoym/FCcUgUoPBxyp1YWPnQlCE32j",
	"rBm11NgWAzrH43FVkWU75ETCMVNHv7jY+aKQf7jMb8ay7V4Jn9botmGJon07YD+Mn32zDfUqpJ4tnUsX",
	"ep6hUAZ+b9dk3NXzb7arffnds6WT/QpWPPkUm0clikreorqlTf74DWPZnVV6NnimPVrNVcWaSC90dAib",
	"fOwokI9X26sBc0WWcbthE0aJUpdYNxlCwREh8LUj5RfznV2R+5JfDpVyYbVrE3NZJ2UBr8sCTtr94iKV",
	"rtMM8Raz3MPKmgyWRIk7JF5R7dkUPqfSo5LOgzNE69zDK5N8QhuM/lIs0Wr06Dp9wkHCNVjkSUotNKiF",
	"+E1p9FzzRgotIyFLBw0h18xLW+hn3mE/FcS55vekgZ2Jqyd33uxFgBAvB6zdHOrkzNvu6NSbH1mSx4Hf",
	"9WTHTOq1QuhInyczb5FnfKli1x6E5ePx8U9H45+Pjv/4lGSUCQxhkYsjo9Vmrqs0apFwJ4mPws2rN0aF",
	"KJLLRElCqi8yb7kWCkOXO08iS/9aoPMvjdg8KjK7c8E+s4CLGLybvf/b0YfpaZC45VA1ZO2Ry9sCt/9i",
	"pty7n3ob1WeGkXC/I5cRyPCZO9DGA9/Dp8bmP7I9DeGUW0tcwWFxeXl51G4dE3gZ1PhirmvlTqNBNeH1",
	"KP36Zk2YpCDVSen672iBxIgJD+zQ0/qo6Q0IkrjGwSUmb63HwXuuyzpCEUqxBZaGD69P4aeffxzDQmpX",
	"rFYyofK8Do4WzaQTWJ2XxRtY23nMochrYH7oufRJd0hGxuxCTTRTjiDSVc0o5taz598v5z9EXGBJuU+z",
	"DApXXVVUE0jGb2VWZODkb5T9h3v74EtnxN7t9oHapPPEeTcI50agChoabz1MrfEmMc141eL289NpSezV",
	"dfN1c2d3rwKo9EXnmub21ay5qrFGFElzU9OrDvoaaeeq6ffsp/13Wn3KutFSVVulk5ZHD9fmJXL/09n/",
	"RTr7Dfq78qBPQd3vOWzEhcWdK1GTcJp9b1CZPFxYtC9W2IAVVpUXQpPRSJF1apyfvBi/OO7cMDBik67v",
	"qKhHLTV9yHdZxUdNKfR95Ko+/55MjAN2KdhJ25Uyr77/YdV/Eqig215t/xkAAP//v5aMu8MgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
