# --------------------------------------------------------------------
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# --------------------------------------------------------------------

FROM {{ .BaseImage }}

# Copy policy definitions
RUN rm -rf /app/policies
COPY policies /app/policies

# Set environment variable for policy directory
ENV GATEWAY_POLICIES_DEFINITIONS__PATH=/app/policies

# Metadata labels
LABEL org.opencontainers.image.title="Gateway Controller with Custom Policies"
LABEL org.opencontainers.image.description="Gateway Controller extended with custom policy definitions"
LABEL build.timestamp="{{ .BuildTimestamp }}"
LABEL build.builder-version="{{ .BuilderVersion }}"
LABEL build.base-image="{{ .BaseImage }}"
{{- range $key, $value := .Labels }}
LABEL {{ $key }}="{{ $value }}"
{{- end }}
