---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.api-platform.wso2.com
  resources:
  - apigateways
  - apikeys
  - certificates
  - llmproviders
  - llmprovidertemplates
  - llmproxies
  - managedsecrets
  - mcps
  - restapis
  - subscriptionplans
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.api-platform.wso2.com
  resources:
  - apigateways/finalizers
  - apikeys/finalizers
  - certificates/finalizers
  - llmproviders/finalizers
  - llmprovidertemplates/finalizers
  - llmproxies/finalizers
  - managedsecrets/finalizers
  - mcps/finalizers
  - restapis/finalizers
  - subscriptionplans/finalizers
  - subscriptions/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.api-platform.wso2.com
  resources:
  - apigateways/status
  - apikeys/status
  - apipolicies/status
  - certificates/status
  - llmproviders/status
  - llmprovidertemplates/status
  - llmproxies/status
  - managedsecrets/status
  - mcps/status
  - restapis/status
  - subscriptionplans/status
  - subscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.api-platform.wso2.com
  resources:
  - apipolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - referencegrants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/finalizers
  - httproutes/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
