package policyv1alpha2

// Body represents HTTP request or response body data
type Body struct {
	// Content is the body payload (may be nil)
	Content []byte

	// EndOfStream indicates if this is the final chunk of body data
	// true = complete body received, false = more chunks may follow
	EndOfStream bool

	// Present indicates if body data is available
	// false = body was not sent or not buffered (e.g., streaming)
	// true = body is available (Content may still be nil for empty bodies)
	Present bool
}

// SharedContext contains data shared across request and response phases
type SharedContext struct {
	// ProjectID is the project ID which the API is associated with
	ProjectID string

	// Unique request identifier for correlation
	// Generated by Kernel, immutable
	RequestID string

	// Shared metadata for inter-policy communication
	// Persists from request phase through response phase
	// Policies read/write this map to coordinate behavior
	Metadata map[string]interface{}

	// API metadata fields (populated by policy engine at request time)
	// These provide context about which API and operation is being processed

	// APIId is the unique identifier of the API (e.g., UUID)
	APIId string

	// APIName is the name of the API (e.g., "PetStore")
	APIName string

	// APIVersion is the version of the API (e.g., "v1.0.0")
	APIVersion string

	// APIKind is the type of the API
	APIKind string

	// APIContext is the base context path of the API (e.g., "/petstore")
	// This is the base path without the version
	APIContext string

	// OperationPath is the operation path pattern from the API definition
	// (e.g., "/pets/{id}" for a parameterized path)
	// This differs from RequestHeaderContext.Path which contains the actual request path
	// with resolved parameters (e.g., "/petstore/v1.0.0/pets/123")
	OperationPath string

	// AuthContext stores structured authentication information populated by auth policies.
	// Nil until an auth policy runs. Use Previous for multi-layer auth chains.
	AuthContext *AuthContext
}

// ─── Request-phase contexts ──────────────────────────────────────────────────

// RequestHeaderContext is passed to RequestHeaderPolicy.OnRequestHeaders.
// The request body is not yet available at this phase.
type RequestHeaderContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string
}

// RequestContext is passed to RequestPolicy.OnRequestBody.
// The complete buffered request body is available.
type RequestContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	Headers   *Headers
	Body      *Body
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string
}

// ─── Response-phase contexts ─────────────────────────────────────────────────

// ResponseHeaderContext is passed to ResponseHeaderPolicy.OnResponseHeaders.
// The response body is not yet available at this phase.
type ResponseHeaderContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int
}

// ResponseContext is passed to ResponsePolicy.OnResponseBody.
// The complete buffered response body is available.
type ResponseContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	ResponseHeaders *Headers

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code
	ResponseStatus int
}

// ─── Streaming contexts ──────────────────────────────────────────────────────

// StreamBody holds a single chunk of body data delivered during streaming processing.
// Unlike Body, it does not carry the "Present" flag — a chunk is always present by definition.
type StreamBody struct {
	// Chunk is the raw bytes for this piece of body data.
	// May be empty when EndOfStream is true (a terminal signal with no payload).
	Chunk []byte

	// EndOfStream signals that no more chunks will follow for this message.
	// Policies should finalize any accumulated state when true.
	EndOfStream bool

	// Index is the zero-based sequential position of this chunk within the stream.
	// The kernel increments this for every chunk delivered to the policy chain.
	// Useful for accumulation logic (e.g. "have I seen enough chunks yet?"),
	// first-chunk initialization, and debug logging.
	Index uint64
}

// RequestStreamContext is the per-chunk context passed to StreamingRequestBodyPolicy.
// It is structurally identical to RequestHeaderContext today, but kept as a distinct
// type so that streaming-specific fields (e.g. accumulated byte count, chunk index)
// can be added in the future without changing the header-phase contract.
// Headers are read-only; body data arrives via the StreamBody argument, not this struct.
type RequestStreamContext struct {
	*SharedContext

	// Current request headers (read-only)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string
}

// ResponseStreamContext is the per-chunk context passed to StreamingResponseBodyPolicy.
// It mirrors ResponseHeaderContext — response body is delivered chunk-by-chunk
// via the StreamBody argument.
type ResponseStreamContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int
}
