/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package policyv1alpha2

import policyenginev1 "github.com/wso2/api-platform/sdk/core/policyengine"

// Body represents HTTP request or response body data
type Body struct {
	// Content is the body payload (may be nil)
	Content []byte

	// EndOfStream indicates if this is the final chunk of body data
	// true = complete body received, false = more chunks may follow
	EndOfStream bool

	// Present indicates if body data is available
	// false = body was not sent or not buffered (e.g., streaming)
	// true = body is available (Content may still be nil for empty bodies)
	Present bool
}

// DownstreamContext identifies the downstream client and carries a snapshot of
// the client request.
type DownstreamContext struct {
	Request *DownstreamRequest
}

// DownstreamRequest holds a snapshot of the request as received from the
// downstream client, captured before any policy mutation is applied.
type DownstreamRequest struct {
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
}

// UpstreamRequestContext identifies the route's resolved upstream target during
// the request phase.
type UpstreamRequestContext struct {
	Name     string
	URL      string
	BasePath string
}

// UpstreamResponseContext identifies the route's resolved upstream target during
// the response phase and carries a snapshot of the upstream response.
type UpstreamResponseContext struct {
	Name     string
	URL      string
	BasePath string
	Response *UpstreamResponse
}

// UpstreamResponse holds a snapshot of the response as received from the
// upstream backend, captured before any policy mutation is applied.
type UpstreamResponse struct {
	Headers    *Headers
	StatusCode int
}

// SharedContext contains data shared across request and response phases
type SharedContext struct {
	// ProjectID is the project ID which the API is associated with
	ProjectID string

	// Unique request identifier for correlation
	// Generated by Kernel, immutable
	RequestID string

	// Shared metadata for inter-policy communication
	// Persists from request phase through response phase
	// Policies read/write this map to coordinate behavior
	Metadata map[string]interface{}

	// API metadata fields (populated by policy engine at request time)
	// These provide context about which API and operation is being processed

	// APIId is the unique identifier of the API (e.g., UUID)
	APIId string

	// APIName is the name of the API (e.g., "PetStore")
	APIName string

	// APIVersion is the version of the API (e.g., "v1.0.0")
	APIVersion string

	// APIKind is the type of the API
	APIKind APIKind

	// APIContext is the base context path of the API (e.g., "/petstore")
	// This is the base path without the version
	APIContext string

	// OperationPath is the operation path pattern from the API definition
	// (e.g., "/pets/{id}" for a parameterized path)
	// This differs from RequestHeaderContext.Path which contains the actual request path
	// with resolved parameters (e.g., "/petstore/v1.0.0/pets/123")
	OperationPath string

	// ResolvedOperation is the canonical protocol operation this request resolved
	// to, on an API kind whose operation cannot be read off the route.
	//
	// OperationPath is not a substitute. A multiplexed transport puts every
	// operation on one path — an A2A JSON-RPC endpoint serves all eleven
	// operations at the same URL — so OperationPath is identical for all of them
	// and the operation is only knowable after the request has been inspected.
	//
	// Written by the policy engine once the request's policy chain has been
	// bound, before any policy in that chain runs, and derived from the same
	// chain key that selected the chain. It therefore cannot name one operation
	// while another operation's policies (its authentication, its rate limits)
	// actually ran.
	//
	// Empty for a route whose chain is fixed by the route itself, which is every
	// API kind that shipped before Agent — so a policy must treat "" as "not
	// applicable", never as a failure.
	ResolvedOperation string

	// ResolutionAttributes are the protocol-derived facts about this request that
	// the route's resolver captured in the same pass that identified the
	// operation — an A2A message's contextId and taskId, for instance.
	//
	// They exist so the request payload is parsed once, and they are the only way
	// a body-sourced value can reach a *request-header-phase* policy, since
	// RequestHeaderContext carries no body of its own. Read via Get, Lookup, Len
	// and Iterate; see ResolutionAttributes for what may be in here, how far it
	// can be trusted, and why it is not a plain map.
	//
	// The zero value is the empty set, which is what a route resolved by the route
	// itself carries — so, as with ResolvedOperation above, a policy reads "no
	// attributes" as "not applicable" rather than as a failure to resolve.
	ResolutionAttributes ResolutionAttributes

	// AuthContext stores structured authentication information populated by auth policies.
	// Nil until an auth policy runs. Use Previous for multi-layer auth chains.
	AuthContext *AuthContext
}

// ─── Request-phase contexts ──────────────────────────────────────────────────

// RequestHeaderContext is passed to RequestHeaderPolicy.OnRequestHeaders.
// The request body is not yet available at this phase.
type RequestHeaderContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// RequestContext is passed to RequestPolicy.OnRequestBody.
// The complete buffered request body is available.
type RequestContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	Headers   *Headers
	Body      *Body
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Deprecated: UpstreamInfo exposes the internal Envoy cluster name and its
	// resolved-upstream shape was incorrect. Use Upstream (*UpstreamRequestContext)
	// instead, which exposes Name rather than the internal cluster name.
	// Retained for backward compatibility; will be removed in a future release.
	UpstreamInfo *policyenginev1.UpstreamInfo

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// ─── Response-phase contexts ─────────────────────────────────────────────────

// ResponseHeaderContext is passed to ResponseHeaderPolicy.OnResponseHeaders.
// The response body is not yet available at this phase.
type ResponseHeaderContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}

// ResponseContext is passed to ResponsePolicy.OnResponseBody.
// The complete buffered response body is available.
type ResponseContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	ResponseHeaders *Headers

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}

// ─── Streaming contexts ──────────────────────────────────────────────────────

// StreamBody holds a single chunk of body data delivered during streaming processing.
// Unlike Body, it does not carry the "Present" flag — a chunk is always present by definition.
type StreamBody struct {
	// Chunk is the raw bytes for this piece of body data.
	// May be empty when EndOfStream is true (a terminal signal with no payload).
	Chunk []byte

	// EndOfStream signals that no more chunks will follow for this message.
	// Policies should finalize any accumulated state when true.
	EndOfStream bool

	// Index is the zero-based sequential position of this chunk within the stream.
	// The kernel increments this for every chunk delivered to the policy chain.
	// Useful for accumulation logic (e.g. "have I seen enough chunks yet?"),
	// first-chunk initialization, and debug logging.
	Index uint64
}

// RequestStreamContext is the per-chunk context passed to StreamingRequestBodyPolicy.
// It is structurally identical to RequestHeaderContext today, but kept as a distinct
// type so that streaming-specific fields (e.g. accumulated byte count, chunk index)
// can be added in the future without changing the header-phase contract.
// Headers are read-only; body data arrives via the StreamBody argument, not this struct.
type RequestStreamContext struct {
	*SharedContext

	// Current request headers (read-only)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// ResponseStreamContext is the per-chunk context passed to StreamingResponseBodyPolicy.
// It mirrors ResponseHeaderContext — response body is delivered chunk-by-chunk
// via the StreamBody argument.
type ResponseStreamContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}

// FaultContext is what a fault policy receives through OnFault.
//
// Its response fields are spelled out rather than embedding ResponseContext, because a fault
// entry reads a response that has already failed and cannot forward it. The names mirror the
// response phase, so a handler moving between the two reads the same values by the same names.
//
// The fields below the response set describe WHY the fault flow is running.
//
// Source says who produced the response; it never says what went wrong:
//
//	Fault.Type    the class of failure — a guardrail, an auth class, "upstream", "routing"
//	Fault.Code    the stable identifier for exactly what went wrong
//	Policy        empty means no policy caused this
//	Source        which actor produced the response
//
// A backend error has a Source and frequently no Fault at all, since the gateway has no
// account of what another service's 500 means. Expect Fault to be nil precisely when Source
// says "backend".
//
// There is deliberately no "trigger" field: which internal phase noticed a failure is an
// engine concern, not something a handler should branch on.
type FaultContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// RequestAuthority, RequestScheme and RequestVhost complete the request identity.
	//
	// They exist on the two REQUEST-phase contexts and on neither response-phase one, so
	// before they were restated here a fault handler could not see them at all — not even
	// for a failure raised in the request header phase, where the phase context sitting
	// three frames up the stack had all three. The gateway keeps every phase context for
	// the life of the request, so it can supply them whatever phase failed.
	//
	// Empty when the request never reached the phase that knows them, which in practice
	// means an engine failure before the header phase ran.
	RequestAuthority string
	RequestScheme    string
	RequestVhost     string

	// Current response headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	ResponseHeaders *Headers

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	//
	// Populated for a REQUEST-phase failure too, where the route resolved a target the
	// request never reached. UpstreamResponseContext is a superset of the request-phase
	// UpstreamRequestContext — same Name, URL and BasePath, plus Response — so the target
	// is reported through the same field on every path, and Response stays nil to say
	// truthfully that no upstream response ever existed. Reading Name/URL/BasePath is what
	// tells a handler which backend a rejected request was bound for.
	Upstream *UpstreamResponseContext

	// OriginalStatus is the status before a policy changed it, and 0 when nothing did.
	// It is not otherwise recoverable — once a guardrail turns a 200 into a 422, the
	// upstream's own status is gone from every downstream view.
	OriginalStatus int
	// Policy names the policy that caused the failure, and is EMPTY when no policy did —
	// a router failure, for instance. Empty means "not caused by a policy", never
	// "unknown": naming a policy for an infrastructure failure would be actively wrong.
	Policy string
	// PolicyVersion is the version of Policy, empty when Policy is.
	PolicyVersion string
	// PolicyPhase names the phase the failing policy was executing in — one of the
	// PolicyPhase constants below. It completes the attribution the two fields above
	// start: which policy, which version, doing what.
	//
	// EMPTY exactly when Policy is empty, and for the same reason. A router failure or an
	// engine error names no policy, so there is no policy phase to name either; filling
	// one in from whatever phase the engine happened to be in would answer a different
	// question — "where did the gateway notice this?" — which is deliberately not on offer
	// (see "Where provenance lives" below).
	//
	// Also empty for a failure raised mid-STREAM, which attributes no policy: once chunks
	// are flowing the engine no longer knows which entry produced the interruption.
	PolicyPhase string
	// ResponseCommitted reports that the status, headers and at least one body chunk have
	// ALREADY reached the client, so nothing this handler returns can change what they see.
	//
	// True only for a failure raised mid-STREAM. It exists because the alternative is a silent
	// trap: a handler that returns modifications or an ImmediateResponse looks correct, compiles,
	// and does nothing — Envoy discards both once a streamed response is in flight. Reading this
	// lets a handler do the part that still works (notify, record, publish) and skip the part
	// that cannot.
	//
	// The gateway logs a warning if a handler tries to change the response while this is true,
	// rather than discarding the attempt quietly.
	ResponseCommitted bool

	// RouteKey is the matched route, for correlating a fault with deployed configuration.
	RouteKey string
	// Source names the actor that produced this error response — one of the FaultSource
	// constants in fault_codes.go. Never empty on the fault path.
	//
	// It is the distinction no status can express: a backend answering 503 and the router
	// failing to reach that backend are both 503, and they mean opposite things. One says the
	// API is up and refusing, the other that the gateway never got there.
	//
	// Also the field an execution condition reads, as error.Source, which is how a chain that
	// should only see the gateway's own failures says so.
	Source string
	// Fault is what the policy that produced the failure said about it — its code, class,
	// direction, summary and detail.
	//
	// Also populated for a ROUTER failure, where there was no policy to say anything: the
	// gateway describes those itself from the proxy's own account (unreachable upstream,
	// timeout, no healthy host), so a handler can report a code and class rather than only a
	// status. Such an error has an empty Policy, per the rule below.
	//
	// nil when nothing described the failure: a policy that has not adopted the type yet, or
	// a BACKEND error, where the gateway deliberately says nothing. Another service's 500 is
	// not the gateway's to classify, and a synthesized code would claim knowledge it does not
	// have — Source reports whose failure it is, and the status and body are what there is.
	//
	// This is the producing policy's own account of the failure, and for a router failure
	// the gateway's. A formatter building the client's body reads it.
	//
	// Its Policy field is gateway-populated and therefore agrees with the Policy field
	// above; it is repeated inside the error so a formatter handed only an FaultDetails
	// still knows what failed.
	Fault *FaultDetails
}

// PolicyPhase values for FaultContext.PolicyPhase: the phase a failing policy was executing
// in when it produced the failure.
//
// These are the existing phase names, not a new vocabulary — the same strings the Python
// SDK's ExecutionPhase carries and the ext_proc Phase enum mirrors, so one failure is
// described the same way whichever side reads it.
//
// Only the phases a policy can be ATTRIBUTED in are listed. A policy rejects from one of
// these four; the remaining phases in that wider enum (needs-more-data, cancel, fault) are
// engine states no policy produces a rejection from, so they can never appear here.
const (
	PolicyPhaseRequestHeaders  = "request_headers"
	PolicyPhaseRequestBody     = "request_body"
	PolicyPhaseResponseHeaders = "response_headers"
	PolicyPhaseResponseBody    = "response_body"
)
