apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: Mcp
metadata:
  name: everything-mcp-v1.0
  namespace: apigateway-demo-apim
  labels:
    gateway.api-platform.wso2.com/restapi-target: wso2-crd-apim
spec:
  displayName: Everything
  version: v1.0
  context: /everything
  specVersion: "2025-06-18"
  upstream:
    url: http://mcp-server-backend:3001/mcp
  tools: []
  resources: []
  prompts: []
