version: v1
gateway:
  version: 1.2.0-beta-SNAPSHOT
policies:
  - name: set-headers
    gomodule: github.com/wso2/gateway-controllers/policies/set-headers@v1
  # Transform payload case Policy
  - name: transform-payload-case
    filePath: ./transform-payload-case
  # Slugify body Python Policy
  - name: slugify-body
    filePath: ./slugify-body
