version: v1
gateway:
  version: 0.7.0-SNAPSHOT
policies:
  - name: add-headers
    gomodule: github.com/wso2/gateway-controllers/policies/add-headers@v0
  # UppercaseBody Policy
  - name: uppercase-body
    filePath: ./uppercase-body
  # CountLetters Policy
  - name: count-letters
    filePath: ./count-letters
