version: v1
gateway:
  version: 1.0.0-rc.2-SNAPSHOT
policies:
  - name: set-headers
    gomodule: github.com/wso2/gateway-controllers/policies/set-headers@v1
  # Transform payload case Policy
  - name: transform-payload-case
    filePath: ./transform-payload-case
