apiVersion: api-portal.api-platform.wso2.com/v1
kind: GraphQL

metadata:
  name: countries-api-v1.0

spec:
  type: GRAPHQL
  displayName: Countries API
  version: v1.0
  description: Query countries, continents, languages, and currencies in a single GraphQL request. Filter by continent, currency, or language code and select exactly the fields you need.
  status: PUBLISHED

  tags:
    - graphql
    - countries
    - geography
    - reference-data

  labels:
    - default

  subscriptionPlans:
    - Silver
    - Bronze

  agentVisibility: VISIBLE

  businessInformation:
    businessOwner: API Team
    businessOwnerEmail: api-team@example.com
    technicalOwner: Platform Team
    technicalOwnerEmail: platform-team@example.com

  endpoints:
    productionUrl: https://db720294-98fd-40f4-85a1-cc6a3b65bc9a-prod.e1-us-east-azure.choreoapis.dev/godzilla/countries-service-nodejs/v1.0
    sandboxUrl: https://db720294-98fd-40f4-85a1-cc6a3b65bc9a-prod.e1-us-east-azure.choreoapis.dev/godzilla/countries-service-nodejs/v1.0
