"""
Talk to sample-service as MCP tools, through the WSO2 AI Gateway.

What this does, in the order an AI agent would do it:

  1. Connect to the gateway's MCP endpoint and shake hands.
  2. Ask "what can you do?"  -> tools/list
  3. Pick a tool and call it  -> tools/call

sample-service itself is a plain REST service and knows nothing about MCP.
The MCP server generated by arazzo-mcp-gen does the translating; the gateway
sits in front of it and governs the traffic.

Run it after setup.sh:

    python3 client.py                     # list tools, then call echo_and_verify
    python3 client.py --tool echo_message # call a specific tool
    python3 client.py --list             # list only
"""

import argparse
import asyncio
import contextlib
import json
import os
import ssl
import sys

try:
    import httpx2
    from mcp import ClientSession
    from mcp.client.streamable_http import streamable_http_client
except ImportError as exc:
    sys.exit(
        f"Could not import a required package: {exc}\n\n"
        "Install the dependencies into a virtual environment:\n"
        "    python3 -m venv .venv && . .venv/bin/activate\n"
        "    python3 -m pip install -r requirements.txt"
    )

TRAFFIC_PORT = os.environ.get("TRAFFIC_PORT", "8443")
GATEWAY_URL = os.environ.get(
    "GATEWAY_MCP_URL", f"https://localhost:{TRAFFIC_PORT}/sample-service/mcp"
)

# The gateway ships with a self-signed certificate, so this sample does not
# verify it. Do not copy this into anything that talks to a real gateway.
_INSECURE_SSL = ssl.create_default_context()
_INSECURE_SSL.check_hostname = False
_INSECURE_SSL.verify_mode = ssl.CERT_NONE


def rule(title):
    print()
    print(f"--- {title} " + "-" * max(0, 60 - len(title)))


def show(payload):
    print(json.dumps(payload, indent=2, default=str))


async def run(tool_name, list_only):
    print(f"Connecting to the gateway at {GATEWAY_URL}")

    async with contextlib.AsyncExitStack() as stack:
        http_client = await stack.enter_async_context(
            httpx2.AsyncClient(verify=_INSECURE_SSL)
        )
        read, write = await stack.enter_async_context(
            streamable_http_client(GATEWAY_URL, http_client=http_client)
        )
        session = await stack.enter_async_context(ClientSession(read, write))

        # 1. Handshake. Both sides agree on a protocol version.
        info = await session.initialize()
        print(f"Connected to: {info.server_info.name} {info.server_info.version}")

        # 2. Discovery. This is the menu the agent had no prior knowledge of.
        rule("Tools the gateway is exposing")
        tools = (await session.list_tools()).tools
        if not tools:
            return (
                "No tools returned. Check that the generated MCP server is "
                "running:  docker logs rest-to-mcp-server"
            )

        for tool in tools:
            summary = (tool.description or "").strip().splitlines()
            headline = summary[0] if summary else "(no description)"
            params = list((tool.input_schema or {}).get("properties", {}))
            print(f"  {tool.name}")
            print(f"      {headline}")
            print(f"      takes: {', '.join(params) or '(nothing)'}")

        if list_only:
            return

        # 3. Invocation.
        chosen = tool_name or (
            "echo_and_verify"
            if any(t.name == "echo_and_verify" for t in tools)
            else tools[0].name
        )
        if not any(t.name == chosen for t in tools):
            return (f"No tool named {chosen!r}. Available: "
                    + ", ".join(t.name for t in tools))

        message = "hello from client.py"
        rule(f"Calling {chosen}")
        print(f'  message = "{message}"')

        result = await session.call_tool(chosen, {"message": message})

        rule("What came back")
        for block in result.content:
            text = getattr(block, "text", None)
            if text is None:
                show(block.model_dump())
                continue
            try:
                show(json.loads(text))
            except (ValueError, TypeError):
                print(text)

        rule("What just happened")
        print("  client.py asked the gateway for a tool list and called one tool.")
        print("  The gateway forwarded both to the generated MCP server.")
        print("  That server ran the Arazzo workflow, which called")
        print("  sample-service over plain HTTP - the same REST endpoints")
        print("  described in arazzo/sample-service-openapi.yaml.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tool", help="Name of the tool to call")
    parser.add_argument("--list", action="store_true", help="List tools and stop")
    args = parser.parse_args()

    try:
        problem = asyncio.run(run(args.tool, args.list))
    except KeyboardInterrupt:
        return
    except Exception as exc:
        sys.exit(
            f"\nFailed: {exc}\n\n"
            "Things to check:\n"
            "  - Did setup.sh finish without errors?\n"
            "  - Is the gateway up?      curl -k https://localhost:"
            f"{TRAFFIC_PORT}/sample-service/mcp\n"
            "  - Is the MCP server up?   docker logs rest-to-mcp-server\n"
            "  - Is the backend up?      curl http://localhost:8090/health\n"
        )

    if problem:
        sys.exit(problem)


if __name__ == "__main__":
    main()
