{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: controller-manager
spec:
  selector:
    app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: webhook-server
{{- end }}
