{{- $g := default (dict) .Values.global -}}
{{- $sa := default (dict) $g.serviceAccount -}}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apip.serviceAccountName" . }}
  labels:
    {{- include "apip.labels" . | nindent 4 }}
  {{- with (include "apip.annotations" (list . $sa.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
{{- end }}
