{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-operator.serviceAccountName" . }}
  labels:
    {{- include "gateway-operator.labels" . | nindent 4 }}
  {{- with (include "gateway-operator.annotations" (list . .Values.serviceAccount.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
