/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Package tlsbackend provides HTTPS backends that require a client certificate and report the
// subject of the one they received, for the gateway's outbound mutual TLS.
//
// Each backend serves its own server certificate and accepts client certificates that chain
// to its own authorities. A request without a certificate, or with one that does not verify,
// is answered 400 without a subject, as a web server that requires client certificates does.
// An accepted request is answered 200 with the subject in the X-Client-Subject header and in
// the body. Responses derive from the request alone, so the service is stateless.
//
// The certificates and authorities arrive in one environment variable, generated by the test
// process so the gateway identities it uploads and the authorities a backend trusts come from
// the same run.
package tlsbackend

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/wso2/api-platform/tests/framework/testbench"
)

// EnvBackends names the environment variable that carries the backends. When it is set, the
// testbench serves these backends and nothing else.
const EnvBackends = "TESTBENCH_TLS_BACKENDS"

// HeaderClientSubject carries the subject of the accepted client certificate.
const HeaderClientSubject = "X-Client-Subject"

// HeaderClientVerified carries "true" or "false" in optional mode: whether the presented
// client certificate verified against the backend's client authorities.
const HeaderClientVerified = "X-Client-Verified"

// HeaderCloseConnection, set to "true" on a request, makes the backend close the connection
// after answering, so the next request reaches it on a connection dialled afresh.
const HeaderCloseConnection = "X-Close-Connection"

// Container ports of the backends.
const (
	PortA         = 8443
	PortB         = 8444
	PortWrongHost = 8445
	PortOptional  = 8446
)

// maxVerifyDepth is the longest accepted chain above the leaf: the leaf, up to two
// intermediates and the root.
const maxVerifyDepth = 3

// Backend is one HTTPS backend as the environment carries it.
type Backend struct {
	// Name identifies the backend in responses and logs, for example "a".
	Name string `json:"name"`
	// Port is the container port it listens on.
	Port int `json:"port"`
	// Certificate is the server certificate, followed by any issuing intermediates.
	Certificate string `json:"certificate"`
	// PrivateKey is the server certificate's key.
	PrivateKey string `json:"privateKey"`
	// ClientCAs are the authorities a client certificate must chain to.
	ClientCAs string `json:"clientCAs"`
	// Optional makes the backend request a client certificate without requiring one: it
	// always answers 200 and reports the subject of whatever leaf certificate was presented,
	// verified or not, in X-Client-Subject and the body, and whether it verified against the
	// backend's client authorities in X-Client-Verified and the body. An empty subject and
	// false mean none was presented.
	Optional bool `json:"optional,omitempty"`
}

// Encode renders backends for EnvBackends.
func Encode(backends []Backend) (string, error) {
	if len(backends) == 0 {
		return "", errors.New("tlsbackend: no backends")
	}
	raw, err := json.Marshal(backends)
	if err != nil {
		return "", fmt.Errorf("tlsbackend: encoding backends: %w", err)
	}
	return string(raw), nil
}

// FromEnv builds one service per backend in an EnvBackends value.
func FromEnv(value string) ([]testbench.Service, error) {
	if strings.TrimSpace(value) == "" {
		return nil, fmt.Errorf("tlsbackend: %s is empty; the test process could not generate the backend certificates", EnvBackends)
	}
	var backends []Backend
	if err := json.Unmarshal([]byte(value), &backends); err != nil {
		return nil, fmt.Errorf("tlsbackend: decoding %s: %w", EnvBackends, err)
	}
	if len(backends) == 0 {
		return nil, fmt.Errorf("tlsbackend: %s lists no backends", EnvBackends)
	}
	services := make([]testbench.Service, 0, len(backends))
	for _, b := range backends {
		svc, err := New(b)
		if err != nil {
			return nil, err
		}
		services = append(services, svc)
	}
	return services, nil
}

// Service is one HTTPS backend.
type Service struct {
	name      string
	port      int
	tlsConfig *tls.Config
	clientCAs *x509.CertPool
	optional  bool
}

// New builds a backend, refusing one without a name, port, server certificate or authority.
func New(b Backend) (*Service, error) {
	if strings.TrimSpace(b.Name) == "" {
		return nil, errors.New("tlsbackend: backend has no name")
	}
	if b.Port <= 0 || b.Port > 65535 {
		return nil, fmt.Errorf("tlsbackend: backend %q has invalid port %d", b.Name, b.Port)
	}
	cert, err := tls.X509KeyPair([]byte(b.Certificate), []byte(b.PrivateKey))
	if err != nil {
		return nil, fmt.Errorf("tlsbackend: backend %q server certificate: %w", b.Name, err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM([]byte(b.ClientCAs)) {
		return nil, fmt.Errorf("tlsbackend: backend %q has no client authority", b.Name)
	}
	return &Service{
		name: b.Name,
		port: b.Port,
		tlsConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
			// Verified per request, so a missing or untrusted certificate is answered 400
			// rather than ending the handshake.
			ClientAuth:       tls.RequestClientCert,
			MinVersion:       tls.VersionTLS12,
			CurvePreferences: []tls.CurveID{tls.X25519MLKEM768, tls.X25519, tls.CurveP256},
		},
		clientCAs: pool,
		optional:  b.Optional,
	}, nil
}

// Name returns the service registration name.
func (s *Service) Name() string { return "tls-backend-" + s.name }

// Port returns the service's listening port.
func (s *Service) Port() int { return s.port }

// Stateful reports that the service keeps no state between requests.
func (s *Service) Stateful() bool { return false }

// TLSConfig returns the listener's server TLS configuration.
func (s *Service) TLSConfig() *tls.Config { return s.tlsConfig }

// Handler answers every path with the verdict on the client certificate.
func (s *Service) Handler() http.Handler {
	return http.HandlerFunc(s.serve)
}

type answer struct {
	Backend string `json:"backend"`
	Client  string `json:"client,omitempty"`
	Error   string `json:"error,omitempty"`
}

// optionalAnswer always carries the client and verified fields.
type optionalAnswer struct {
	Backend  string `json:"backend"`
	Client   string `json:"client"`
	Verified bool   `json:"verified"`
}

func (s *Service) serve(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if r.Header.Get(HeaderCloseConnection) == "true" {
		w.Header().Set("Connection", "close")
	}
	if s.optional {
		var presented string
		if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
			presented = r.TLS.PeerCertificates[0].Subject.String()
		}
		_, verifyErr := s.clientSubject(r.TLS)
		verified := verifyErr == nil
		w.Header().Set(HeaderClientSubject, presented)
		w.Header().Set(HeaderClientVerified, strconv.FormatBool(verified))
		w.WriteHeader(http.StatusOK)
		if encodeErr := json.NewEncoder(w).Encode(optionalAnswer{Backend: s.name, Client: presented, Verified: verified}); encodeErr != nil {
			testbench.ServiceLogger(r.Context()).Warn("tls backend response failed", "error", encodeErr)
		}
		return
	}
	subject, err := s.clientSubject(r.TLS)
	out, status := answer{Backend: s.name, Client: subject}, http.StatusOK
	if err != nil {
		testbench.ServiceLogger(r.Context()).Info("tls backend refused the client certificate",
			"backend", s.name, "reason", err.Error())
		out, status = answer{Backend: s.name, Error: err.Error()}, http.StatusBadRequest
	} else {
		w.Header().Set(HeaderClientSubject, subject)
	}
	w.WriteHeader(status)
	if encodeErr := json.NewEncoder(w).Encode(out); encodeErr != nil {
		testbench.ServiceLogger(r.Context()).Warn("tls backend response failed", "error", encodeErr)
	}
}

// clientSubject verifies the presented chain against the backend's authorities and returns
// the leaf's subject in RFC 2253 form.
func (s *Service) clientSubject(state *tls.ConnectionState) (string, error) {
	if state == nil || len(state.PeerCertificates) == 0 {
		return "", errors.New("no required SSL certificate was sent")
	}
	leaf := state.PeerCertificates[0]
	intermediates := x509.NewCertPool()
	for _, c := range state.PeerCertificates[1:] {
		intermediates.AddCert(c)
	}
	chains, err := leaf.Verify(x509.VerifyOptions{
		Roots: s.clientCAs, Intermediates: intermediates,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	})
	if err != nil {
		return "", fmt.Errorf("the SSL certificate error: %w", err)
	}
	for _, chain := range chains {
		if len(chain) <= maxVerifyDepth+1 {
			return leaf.Subject.String(), nil
		}
	}
	return "", fmt.Errorf("the SSL certificate error: chain longer than %d", maxVerifyDepth)
}
