version: v1
policies:
  - name: basic-auth
    gomodule: github.com/wso2/gateway-controllers/policies/basic-auth@v1.0.1
  - name: set-headers
    gomodule: github.com/wso2/gateway-controllers/policies/set-headers@v1.0.1
  - name: api-key-auth
    gomodule: github.com/wso2/gateway-controllers/policies/api-key-auth@v1.0.1
  - name: advanced-ratelimit
    gomodule: github.com/wso2/gateway-controllers/policies/advanced-ratelimit@v1
  - name: analytics-header-filter
    gomodule: github.com/wso2/gateway-controllers/policies/analytics-header-filter@v1
  - name: basic-ratelimit
    gomodule: github.com/wso2/gateway-controllers/policies/basic-ratelimit@v1
  - name: cors
    gomodule: github.com/wso2/gateway-controllers/policies/cors@v1
  - name: interceptor-service
    gomodule: github.com/wso2/gateway-controllers/policies/interceptor-service@v1
  - name: json-xml-mediator
    gomodule: github.com/wso2/gateway-controllers/policies/json-xml-mediator@v1
  - name: jwt-auth
    gomodule: github.com/wso2/gateway-controllers/policies/jwt-auth@v1
  - name: log-message
    gomodule: github.com/wso2/gateway-controllers/policies/log-message@v1
  - name: remove-headers
    gomodule: github.com/wso2/gateway-controllers/policies/remove-headers@v1
  - name: subscription-validation
    gomodule: github.com/wso2/gateway-controllers/policies/subscription-validation@v1
  - name: websub-hmac-auth
    gomodule: github.com/wso2/gateway-controllers/policies/websub-hmac-auth@v1
