/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package dto

// CreateAPIKeyRequest represents the request to register an external API key.
// This is used when external platforms inject API keys to hybrid gateways.
type CreateAPIKeyRequest struct {
	// Name is the unique identifier for this API key within the API (optional; if omitted, generated from displayName)
	Name string `json:"name,omitempty"`

	// DisplayName is the display name of the API key
	DisplayName string `json:"displayName,omitempty"`

	// ApiKey is the plain text API key value that will be hashed before storage
	ApiKey string `json:"apiKey" binding:"required"`

	// ExternalRefId is an optional reference ID for tracing purposes (from external platforms)
	ExternalRefId *string `json:"externalRefId,omitempty"`

	// Operations specifies which API operations this key can access (default: "*" for all)
	Operations string `json:"operations,omitempty"`

	// ExpiresAt is the optional expiration time in ISO 8601 format
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

// CreateAPIKeyResponse represents the response after registering an API key.
type CreateAPIKeyResponse struct {
	// Status indicates the result of the operation ("success" or "error")
	Status string `json:"status"`

	// Message provides additional details about the operation result
	Message string `json:"message"`

	// KeyId is the internal ID generated by the gateway for tracking
	KeyId string `json:"keyId,omitempty"`
}

// UpdateAPIKeyRequest represents the request to update/regenerate an API key.
// This is used when external platforms rotate API keys on hybrid gateways.
type UpdateAPIKeyRequest struct {
	// ApiKey is the new plain text API key value that will be hashed before storage
	ApiKey string `json:"apiKey" binding:"required"`

	// ExpiresAt is the optional expiration time in ISO 8601 format
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

// UpdateAPIKeyResponse represents the response after updating an API key.
type UpdateAPIKeyResponse struct {
	// Status indicates the result of the operation ("success" or "error")
	Status string `json:"status"`

	// Message provides additional details about the operation result
	Message string `json:"message"`

	// KeyId is the internal ID of the updated key
	KeyId string `json:"keyId,omitempty"`
}

// RevokeAPIKeyResponse represents the response after revoking an API key.
type RevokeAPIKeyResponse struct {
	// Status indicates the result of the operation ("success" or "error")
	Status string `json:"status"`

	// Message provides additional details about the operation result
	Message string `json:"message"`
}

// APIKeyCreatedEventDTO represents the event payload for apikey.created.
// This is sent over WebSocket to notify gateways of new API keys.
type APIKeyCreatedEventDTO struct {
	// ApiId identifies the API this key belongs to
	ApiId string `json:"apiId"`

	// Name is the unique name of the API key
	Name string `json:"name"`

	// DisplayName is the display name of the API key
	DisplayName string `json:"displayName"`

	// HashedApiKey is the SHA256 hashed API key for secure storage
	HashedApiKey string `json:"hashedApiKey"`

	// ExternalRefId is an optional reference ID for tracing
	ExternalRefId *string `json:"externalRefId,omitempty"`

	// Operations specifies which API operations this key can access
	Operations string `json:"operations"`

	// ExpiresAt is the optional expiration time in ISO 8601 format
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

// APIKeyRevokedEventDTO represents the event payload for apikey.revoked.
// This is sent over WebSocket to notify gateways of revoked API keys.
type APIKeyRevokedEventDTO struct {
	// ApiId identifies the API this key belongs to
	ApiId string `json:"apiId"`

	// KeyName is the unique name of the API key that was revoked
	KeyName string `json:"keyName"`
}
