package policyv1alpha

// Body represents HTTP request or response body data
type Body struct {
	// Content is the body payload (may be nil)
	Content []byte

	// EndOfStream indicates if this is the final chunk of body data
	// true = complete body received, false = more chunks may follow
	EndOfStream bool

	// Present indicates if body data is available
	// false = body was not sent or not buffered (e.g., streaming)
	// true = body is available (Content may still be nil for empty bodies)
	Present bool
}

// AuthContext holds authentication data produced by auth policies (jwt, oauth2, apikey, basic-auth)
// and consumed by downstream policies (analytics, rate limiting, etc.).
type AuthContext struct {
	// Authenticated indicates whether the request passed authentication.
	Authenticated bool

	// AuthType identifies the mechanism that authenticated the request.
	// Values: "jwt", "oauth2", "apikey", "basic", or empty if unauthenticated.
	AuthType string

	// Subject is the authenticated principal identifier.
	// JWT "sub" claim, basic-auth username, API key owner/app ID, etc.
	Subject string

	// Issuer is the token issuer (JWT "iss" claim, IdP URL).
	// Empty for non-token auth types.
	Issuer string

	// Audience is the intended audience (JWT "aud" claim).
	// Empty for non-token auth types.
	Audience string

	// Scopes contains granted OAuth2/JWT scopes as a set for O(1) lookup.
	// Nil for non-token auth types.
	Scopes map[string]bool

	// AppID is the application identifier associated with the authenticated request.
	// For API key auth, this is the application that owns the key.
	// For OAuth2, this may be the client_id. Empty if not applicable.
	AppID string

	// UserID is the user identifier associated with the authenticated request.
	// By default, this is the same as Subject, but can be set separately by auth policies if needed.
	UserID string

	// Properties holds additional auth-related key-value data for
	// inter-policy communication that does not fit the typed fields above.
	// Examples: email, custom JWT claims, API key tier.
	Properties map[string]string
}

// SharedContext contains data shared across request and response phases
type SharedContext struct {
	// ProjectID is the project ID which the API is associated with
	ProjectID string

	// Unique request identifier for correlation
	// Generated by Kernel, immutable
	RequestID string

	// Shared metadata for inter-policy communication
	// Persists from request phase through response phase
	// Policies read/write this map to coordinate behavior
	Metadata map[string]interface{}

	// API metadata fields (populated by policy engine at request time)
	// These provide context about which API and operation is being processed

	// APIId is the unique identifier of the API (e.g., UUID)
	APIId string

	// APIName is the name of the API (e.g., "PetStore")
	APIName string

	// APIVersion is the version of the API (e.g., "v1.0.0")
	APIVersion string

	// APIKind is the type of the API
	APIKind string

	// APIContext is the base context path of the API (e.g., "/petstore")
	// This is the base path without the version
	APIContext string

	// OperationPath is the operation path pattern from the API definition
	// (e.g., "/pets/{id}" for a parameterized path)
	// This differs from RequestContext.Path which contains the actual request path
	// with resolved parameters (e.g., "/petstore/v1.0.0/pets/123")
	OperationPath string

	// AuthContext stores authentication-related information
	// Populated by auth policies, consumed by downstream policies
	AuthContext *AuthContext
}

// RequestContext is mutable context for request phase containing current request state
type RequestContext struct {
	// Shared data across request/response lifecycle
	*SharedContext

	// Current request headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	Headers   *Headers
	Body      *Body
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string
}

// ResponseContext is context for response phase containing request and response state
type ResponseContext struct {
	// Shared data across request/response lifecycle
	*SharedContext

	// Original request data (immutable, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	ResponseHeaders *Headers

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code (mutable)
	ResponseStatus int
}
