package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/signal"
	"syscall"

	extprocv3 "github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3"
	"google.golang.org/grpc"

	"github.com/yourorg/policy-engine/kernel"
	"github.com/yourorg/policy-engine/pkg/cel"
	"github.com/yourorg/policy-engine/worker/core"
)

// T091: Command-line flags implementation
var (
	extprocPort = flag.Int("extproc-port", 9001, "Port for ext_proc gRPC server")
	xdsPort     = flag.Int("xds-port", 9002, "Port for xDS policy discovery server (future)")
	configFile  = flag.String("config-file", "configs/policy-chains.yaml", "Path to policy chain configuration file")
)

// T090: Main entry point with gRPC server initialization
func main() {
	flag.Parse()

	// Set up structured logging with slog
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)
	ctx := context.Background()

	slog.InfoContext(ctx, "Policy Engine starting")
	slog.InfoContext(ctx, "Configuration", "extproc_port", *extprocPort, "config_file", *configFile)

	// Initialize components
	// T093: Wire Kernel and Core components
	k := kernel.NewKernel()
	registry := core.GetRegistry()

	// Initialize CEL evaluator
	celEvaluator, err := cel.NewCELEvaluator()
	if err != nil {
		slog.ErrorContext(ctx, "Failed to create CEL evaluator", "error", err)
		os.Exit(1)
	}

	// Initialize core execution engine
	coreEngine := core.NewCore(registry, celEvaluator)

	// Register sample policies from policy directory
	// NOTE: In production, this would be auto-generated by the Builder
	// For now, we load policy definitions from YAML files but skip implementations
	// since they need to be compiled in via the Builder
	slog.InfoContext(ctx, "Policy registration would happen here via Builder-generated code")

	// Load policy definitions from directory
	if err := registry.RegisterFromDirectory("policies"); err != nil {
		slog.WarnContext(ctx, "Failed to register policies from directory", "error", err)
		slog.WarnContext(ctx, "This is expected if policies haven't been compiled via Builder")
	}

	// Load policy chain configuration from file
	configLoader := kernel.NewConfigLoader(k, registry, coreEngine)
	if err := configLoader.LoadFromFile(*configFile); err != nil {
		slog.ErrorContext(ctx, "Failed to load configuration", "error", err)
		os.Exit(1)
	}

	// Create ext_proc gRPC server
	extprocServer := kernel.NewExternalProcessorServer(k, coreEngine)

	// Start gRPC server
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", *extprocPort))
	if err != nil {
		slog.ErrorContext(ctx, "Failed to listen on port", "port", *extprocPort, "error", err)
		os.Exit(1)
	}

	grpcServer := grpc.NewServer()

	// Register ext_proc service
	extprocv3.RegisterExternalProcessorServer(grpcServer, extprocServer)

	slog.InfoContext(ctx, "Policy Engine listening", "port", *extprocPort)

	// T092: Graceful shutdown handling
	// Setup signal handling for graceful shutdown
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	// Start server in goroutine
	go func() {
		if err := grpcServer.Serve(lis); err != nil {
			slog.ErrorContext(ctx, "Failed to serve", "error", err)
			os.Exit(1)
		}
	}()

	// Wait for shutdown signal
	sig := <-sigChan
	slog.InfoContext(ctx, "Received signal, shutting down gracefully", "signal", sig)

	// Graceful shutdown
	grpcServer.GracefulStop()
	slog.InfoContext(ctx, "Policy Engine shut down successfully")
}
