package policy

// Body represents HTTP request or response body data
type Body struct {
	// Content is the body payload (may be nil)
	Content []byte

	// EndOfStream indicates if this is the final chunk of body data
	// true = complete body received, false = more chunks may follow
	EndOfStream bool

	// Present indicates if body data is available
	// false = body was not sent or not buffered (e.g., streaming)
	// true = body is available (Content may still be nil for empty bodies)
	Present bool
}

// SharedContext contains data shared across request and response phases
type SharedContext struct {
	// Unique request identifier for correlation
	// Generated by Kernel, immutable
	RequestID string

	// Shared metadata for inter-policy communication
	// Persists from request phase through response phase
	// Policies read/write this map to coordinate behavior
	Metadata map[string]interface{}
}

// RequestContext is mutable context for request phase containing current request state
type RequestContext struct {
	// Shared data across request/response lifecycle
	*SharedContext

	// Current request headers (mutable)
	// Updated in-place as policies execute
	// Key: header name (lowercase), Value: header values (array)
	Headers map[string][]string

	// Current request body (mutable)
	// nil if no body or body not required
	// Updated in-place by body-modifying policies
	Body *Body

	// Current request path (mutable)
	// Can be modified by routing policies
	Path string

	// Current request method (mutable)
	// Can be modified by transformation policies
	Method string
}

// ResponseContext is context for response phase containing request and response state
type ResponseContext struct {
	// Shared data across request/response lifecycle
	*SharedContext

	// Original request data (immutable, from request phase)
	RequestHeaders map[string][]string
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (mutable)
	// Updated in-place as policies execute
	ResponseHeaders map[string][]string

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code (mutable)
	ResponseStatus int
}
