apiVersion: gateway.api-platform.wso2.com/v1
kind: Mcp
metadata:
  name: reading-list-mcp-v1.0
spec:
  displayName: Reading List MCP
  version: v1.0
  context: /reading-list
  specVersion: "2025-06-18"
  upstream:
    url: http://mock-mcp-reading-list:8080
  policies:
    - name: mcp-auth
      version: v1
      params:
        issuers:
          - mock-jwks
  tools: []
  resources: []
  prompts: []
