name: Run Gosec
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  gateway-controller:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    defaults:
      run:
        working-directory: gateway/gateway-controller
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec
        run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gateway/gateway-controller/results.sarif
          category: gateway-controller

  policy-engine:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    defaults:
      run:
        working-directory: gateway/gateway-runtime/policy-engine
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec
        run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gateway/gateway-runtime/policy-engine/results.sarif
          category: policy-engine

  gateway-builder:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    defaults:
      run:
        working-directory: gateway/gateway-builder
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec
        run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gateway/gateway-builder/results.sarif
          category: gateway-builder

  platform-api:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    defaults:
      run:
        working-directory: platform-api/src
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec
        run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: platform-api/src/results.sarif
          category: platform-api

  event-gateway-runtime:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    defaults:
      run:
        working-directory: event-gateway/gateway-runtime
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec
        run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: event-gateway/gateway-runtime/results.sarif
          category: event-gateway-runtime
