name: Trivy Scan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  scan-policy-engine:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      # IMPORTANT: network=host lets buildkit reach localhost:5000
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build & push gateway-runtime image
        run: |
          export RUNTIME_IMAGE=localhost:5000/policy-engine
          export RUNTIME_TAG=$RUNTIME_IMAGE:trivy
          make -C gateway/gateway-runtime build-and-push-multiarch \
          RUNTIME_IMAGE=localhost:5000/policy-engine \
          RUNTIME_TAG=localhost:5000/policy-engine:trivy

      - name: Trivy scan policy-engine
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/policy-engine:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Build & push gateway-controller
        run: |
          make -C gateway/gateway-controller build-and-push-multiarch \
          IMAGE_NAME=localhost:5000/gateway-controller \
          VERSION=trivy

      - name: Trivy scan gateway-controller
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/gateway-controller:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Build & push gateway-builder
        run: |
          make -C gateway/gateway-builder build-and-push-multiarch \
          IMAGE_NAME=localhost:5000/gateway-builder \
          VERSION=trivy

      - name: Trivy scan gateway-builder
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/gateway-builder:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Trivy scan router
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/router:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Build & push event-gateway-runtime
        run: |
          make -C event-gateway/gateway-runtime build-and-push-multiarch \
          IMAGE_NAME=localhost:5000/event-gateway-runtime \
          VERSION=trivy

      - name: Trivy scan event-gateway-runtime
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/event-gateway-runtime:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Build & push event-gateway-controller
        run: |
          cd gateway/gateway-controller && \
          docker buildx build -f Dockerfile \
            --build-context sdk=../../sdk \
            --build-context sdk-core=../../sdk/core \
            --build-context common=../../common \
            --build-context build-manifest=.. \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=trivy \
            --target production \
            -t localhost:5000/event-gateway-controller:trivy \
            --push \
            .

      - name: Trivy scan event-gateway-controller
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/event-gateway-controller:trivy'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
